using System.Collections.Generic;
using System.Linq;
using Dormant.SourceGeneration.Emit;
using Dormant.SourceGeneration.Ir;
using Dormant.SourceGeneration.Ir.Dialects;
using Dormant.SourceGeneration.Parsing;

namespace Dormant.SourceGeneration.Schema;

/// <summary>
/// Emits a per-entity <c>IEntityBinding&lt;TEntity&gt;</c> (registered via a <c>[ModuleInitializer]</c>):
/// read + schema metadata only (002 fork) — no-reflection materialization (delegates to the entity's
/// generated ctor), the schema-qualified SELECT-by-primary-key statement, the module schema name, and the
/// prebuilt <c>CREATE TABLE</c> DDL. The DDL and the SELECT-by-key statement are emitted as per-dialect
/// variant switches keyed by the requested <c>DialectId</c> (005 D4). Writes are authored DQL commands,
/// not part of the binding. Database names are schema-qualified + convention-resolved.
/// </summary>
internal static class EntityBindingEmitter
{
    private const string Abs = "global::Dormant.Abstractions";
    private const string Stmt = "global::Dormant.Abstractions.Querying.PreparedStatement";
    private const string DialectId = "global::Dormant.Abstractions.Providers.DialectId";

    public static string Emit(
        string @namespace,
        EntityModel entity,
        string schema,
        NamingConvention convention,
        IReadOnlyDictionary<string, string> refPkDslTypes
    )
    {
        var key = entity.Properties.FirstOrDefault(p => p.IsPrimary);
        var columns = entity.Properties; // value columns, declaration order
        var tableRef = new TableRef(schema, Table(entity, convention));
        // Full-entity read layout: value columns then the to-one `<ref>_id` FK columns (009 P-A) — the same
        // order the entity materializer ctor reads.
        var colNames = EntityColumns.SelectColumnNames(entity, convention);

        // Value columns (declaration order) followed by a `<ref>_id` foreign-key column for each single
        // reference (FR-020): typed as the target entity's primary-key DormantQL type (the renderer maps it
        // per dialect), NOT NULL iff the ref is required. Reads materialize value columns only; the FK
        // column is written by commands, read via the relationship.
        var ddlColumns = columns
            .Select(p => new ColumnDef(Col(p, convention), p.DslType, !p.IsNullable, p.IsPrimary))
            .ToList();
        foreach (var reference in entity.References.Where(r => r.Kind == ReferenceKind.Ref))
        {
            var fkDslType = refPkDslTypes.TryGetValue(reference.TargetEntity, out var t)
                ? t
                : "uuid";
            ddlColumns.Add(
                new ColumnDef(
                    NamingConventions.Resolve(reference.Name, null, convention) + "_id",
                    fkDslType,
                    reference.IsRequired,
                    false
                )
            );
        }

        var createTable = new CreateTableStatement(
            tableRef,
            ddlColumns,
            BuildTableConstraints(entity, convention)
        );

        var writer = new SourceWriter()
            .Line("// <auto-generated/>")
            .Line("#nullable enable")
            .Line()
            .Line($"namespace {@namespace};")
            .Line()
            .Open(
                $"internal sealed class {entity.Name}Binding : {Abs}.Entities.IEntityBinding<{entity.Name}>"
            )
            .Line("[global::System.Runtime.CompilerServices.ModuleInitializer]")
            .Line(
                $"internal static void Register() => {Abs}.Entities.EntityBindings.Register<{entity.Name}>(new {entity.Name}Binding());"
            )
            .Line()
            .Line($"public string Schema => {Quote(schema)};")
            .Line();

        EmitCreateSchemaSql(writer, new CreateSchemaStatement(schema));
        EmitCreateTableSql(writer, createTable);
        EmitMaterialize(writer, entity);
        EmitSelectByKey(writer, entity, tableRef, colNames, key, convention);

        return writer.Close().ToString();
    }

    // Feature 012 (Slice 2): lower member-level constraints to table-level DDL constraints.
    // Covered here: `unique` → UNIQUE; numeric bounds + length → CHECK. `primary`/`concurrency` stay
    // on the column (handled above). `one_of`/`regex`/`check`-expr + entity-level constraints are not
    // yet lowered (later slices). CheckSql uses double-quoted identifiers — shared by PostgreSQL and
    // SQLite (both quote with "), so it is dialect-neutral for the current providers.
    private static List<ConstraintDef>? BuildTableConstraints(
        EntityModel entity,
        NamingConvention convention
    )
    {
        var result = new List<ConstraintDef>();
        var table = Table(entity, convention);
        var colByMember = new Dictionary<string, string>();
        foreach (var p in entity.Properties)
        {
            colByMember[p.Name] = Col(p, convention);
        }

        foreach (var property in entity.Properties)
        {
            if (property.Constraints.Count == 0)
            {
                continue;
            }

            var col = Col(property, convention);
            var qcol = "\"" + col + "\"";

            foreach (var c in property.Constraints)
            {
                switch (c.Kind)
                {
                    case ConstraintKind.Unique:
                        result.Add(
                            new ConstraintDef(
                                ConstraintIrKind.Unique,
                                [col],
                                null,
                                c.SqlName ?? $"{table}_{col}_key"
                            )
                        );
                        break;
                    case ConstraintKind.Max:
                        AddCheck(result, c, $"{qcol} <= {Arg(c, "max", 0)}", table, col, "max");
                        break;
                    case ConstraintKind.Min:
                        AddCheck(result, c, $"{qcol} >= {Arg(c, "min", 0)}", table, col, "min");
                        break;
                    case ConstraintKind.MaxExclusive:
                        AddCheck(result, c, $"{qcol} < {Arg(c, "max", 0)}", table, col, "maxx");
                        break;
                    case ConstraintKind.MinExclusive:
                        AddCheck(result, c, $"{qcol} > {Arg(c, "min", 0)}", table, col, "minx");
                        break;
                    case ConstraintKind.MaxLength:
                        AddCheck(
                            result,
                            c,
                            $"length({qcol}) <= {Arg(c, "value", 0)}",
                            table,
                            col,
                            "maxlen"
                        );
                        break;
                    case ConstraintKind.MinLength:
                        AddCheck(
                            result,
                            c,
                            $"length({qcol}) >= {Arg(c, "value", 0)}",
                            table,
                            col,
                            "minlen"
                        );
                        break;
                    case ConstraintKind.Length:
                        AddCheck(
                            result,
                            c,
                            $"length({qcol}) = {Arg(c, "value", 0)}",
                            table,
                            col,
                            "len"
                        );
                        break;
                    case ConstraintKind.Range:
                        AddCheck(
                            result,
                            c,
                            $"{qcol} >= {Arg(c, "min", 0)} AND {qcol} <= {Arg(c, "max", 1)}",
                            table,
                            col,
                            "range"
                        );
                        break;
                    case ConstraintKind.OneOf:
                        AddCheck(result, c, $"{qcol} IN ({OneOfValues(c)})", table, col, "oneof");
                        break;
                    case ConstraintKind.Regex:
                        result.Add(
                            new ConstraintDef(
                                ConstraintIrKind.Regex,
                                [col],
                                c.Args.Count > 0 ? c.Args[0].Value : string.Empty,
                                c.SqlName ?? $"{table}_{col}_regex"
                            )
                        );
                        break;
                    case ConstraintKind.Check:
                        AddCheck(
                            result,
                            c,
                            RenderCheckSql(c.CheckTokens, colByMember),
                            table,
                            col,
                            "check"
                        );
                        break;
                    // Primary/Concurrency handled on the column.
                }
            }
        }

        // Entity-level constraints (Feature 012 US2): composite UNIQUE / PRIMARY KEY over `on (…)`
        // members, plus a cross-field `check (…)` expression.
        if (entity.Constraints.Count > 0)
        {
            foreach (var ec in entity.Constraints)
            {
                if (ec.Kind == ConstraintKind.Check)
                {
                    result.Add(
                        new ConstraintDef(
                            ConstraintIrKind.Check,
                            [],
                            RenderCheckSql(ec.CheckTokens, colByMember),
                            ec.SqlName ?? $"{table}_check"
                        )
                    );
                    continue;
                }

                if (ec.Targets.Count == 0)
                {
                    continue;
                }

                var cols = new List<string>();
                var resolved = true;
                foreach (var t in ec.Targets)
                {
                    if (colByMember.TryGetValue(t, out var cc))
                    {
                        cols.Add(cc);
                    }
                    else
                    {
                        resolved = false;
                    }
                }

                if (!resolved || cols.Count == 0)
                {
                    continue;
                }

                var joined = string.Join("_", cols);
                if (ec.Kind == ConstraintKind.Unique)
                {
                    result.Add(
                        new ConstraintDef(
                            ConstraintIrKind.Unique,
                            cols,
                            null,
                            ec.SqlName ?? $"{table}_{joined}_key"
                        )
                    );
                }
                else if (ec.Kind == ConstraintKind.Primary)
                {
                    result.Add(
                        new ConstraintDef(
                            ConstraintIrKind.PrimaryKey,
                            cols,
                            null,
                            ec.SqlName ?? $"{table}_pkey"
                        )
                    );
                }
            }
        }

        return result.Count > 0 ? result : null;
    }

    // Translates a captured `check (…)` token stream to SQL: identifiers → quoted columns (resolved
    // via the entity's member→column map), string literals → quoted+escaped, operators already SQL.
    private static string RenderCheckSql(
        EquatableArray<CheckToken> tokens,
        Dictionary<string, string> colByMember
    )
    {
        var parts = new List<string>();
        foreach (var t in tokens)
        {
            switch (t.Kind)
            {
                case CheckTokenKind.Identifier:
                    var col = colByMember.TryGetValue(t.Text, out var c) ? c : t.Text;
                    parts.Add("\"" + col + "\"");
                    break;
                case CheckTokenKind.String:
                    parts.Add("'" + t.Text.Replace("'", "''") + "'");
                    break;
                default:
                    parts.Add(t.Text);
                    break;
            }
        }

        return string.Join(" ", parts);
    }

    // Renders the value list for a `one_of(...)` CHECK, quoting string literals and escaping quotes.
    private static string OneOfValues(ConstraintModel c)
    {
        var parts = new List<string>();
        foreach (var a in c.Args)
        {
            parts.Add(a.IsString ? "'" + a.Value.Replace("'", "''") + "'" : a.Value);
        }

        return string.Join(", ", parts);
    }

    private static void AddCheck(
        List<ConstraintDef> result,
        ConstraintModel c,
        string checkSql,
        string table,
        string col,
        string suffix
    ) =>
        result.Add(
            new ConstraintDef(
                ConstraintIrKind.Check,
                [col],
                checkSql,
                c.SqlName ?? $"{table}_{col}_{suffix}"
            )
        );

    // Resolves a constraint argument by named key, then by positional index; "" when absent.
    private static string Arg(ConstraintModel c, string name, int positional)
    {
        var pos = 0;
        foreach (var a in c.Args)
        {
            if (a.Name == name)
            {
                return a.Value;
            }
        }

        foreach (var a in c.Args)
        {
            if (a.Name is null)
            {
                if (pos == positional)
                {
                    return a.Value;
                }

                pos++;
            }
        }

        return "0";
    }

    private static string Table(EntityModel entity, NamingConvention convention) =>
        NamingConventions.Resolve(entity.Name, entity.NameOverride, convention);

    private static string Col(PropertyModel property, NamingConvention convention) =>
        NamingConventions.Resolve(property.Name, property.NameOverride, convention);

    private static void EmitCreateSchemaSql(SourceWriter writer, CreateSchemaStatement createSchema)
    {
        writer.Line($"public string CreateSchemaSql({DialectId} dialect) =>");
        DialectSwitch.WriteStatementArg(writer, "    ", "dialect", createSchema, ";");
        writer.Line();
    }

    private static void EmitCreateTableSql(SourceWriter writer, CreateTableStatement createTable)
    {
        writer.Line($"public string CreateTableSql({DialectId} dialect) =>");
        DialectSwitch.WriteStatementArg(writer, "    ", "dialect", createTable, ";");
        writer.Line();
    }

    private static void EmitMaterialize(SourceWriter writer, EntityModel entity)
    {
        // Delegates to the entity's generated ctor; reads value columns positionally in SELECT order.
        writer
            .Open($"public {entity.Name} Materialize({Abs}.Querying.IFieldReader reader)")
            .Line($"return new {entity.Name}(reader);")
            .Close()
            .Line();
    }

    private static void EmitSelectByKey(
        SourceWriter writer,
        EntityModel entity,
        TableRef table,
        IReadOnlyList<string> colNames,
        PropertyModel? key,
        NamingConvention convention
    )
    {
        writer.Open($"public {Stmt} SelectByKey({DialectId} dialect, object key)");
        if (key is null)
        {
            writer.Line(
                "throw new global::System.NotSupportedException(\"Entity has no single primary key.\");"
            );
        }
        else
        {
            var select = new SelectStatement(
                table,
                colNames,
                [new SqlCondition(Col(key, convention), "=", 1)],
                [],
                Limit: null,
                Offset: null
            );
            writer.Line($"return new {Stmt}(");
            DialectSwitch.WriteStatementArg(writer, "    ", "dialect", select, ",");
            writer.Line($"    writer => writer.Write(1, ({key.ClrType})key));");
        }

        writer.Close();
    }

    private static string Quote(string text) =>
        "\"" + text.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
