using System.Collections.Generic;
using System.Linq;
using Dormant.SourceGeneration.Emit;
using Dormant.SourceGeneration.Ir;
using Dormant.SourceGeneration.Ir.Dialects;
using Dormant.SourceGeneration.Parsing;

namespace Dormant.SourceGeneration.Schema;

/// <summary>
/// Emits a per-entity <c>IEntityBinding&lt;TEntity&gt;</c> (registered via a <c>[ModuleInitializer]</c>):
/// read + schema metadata only (002 fork) — no-reflection materialization (delegates to the entity's
/// generated ctor), the schema-qualified SELECT-by-primary-key statement, the module schema name, and the
/// prebuilt <c>CREATE TABLE</c> DDL. The DDL and the SELECT-by-key statement are emitted as per-dialect
/// variant switches keyed by the requested <c>DialectId</c> (005 D4). Writes are authored DQL commands,
/// not part of the binding. Database names are schema-qualified + convention-resolved.
/// </summary>
internal static class EntityBindingEmitter
{
    private const string Abs = "global::Dormant.Abstractions";
    private const string Stmt = "global::Dormant.Abstractions.Querying.PreparedStatement";
    private const string DialectId = "global::Dormant.Abstractions.Providers.DialectId";

    public static string Emit(
        string @namespace,
        EntityModel entity,
        string schema,
        NamingConvention convention,
        IReadOnlyDictionary<string, string> refPkDslTypes
    )
    {
        var key = entity.Properties.FirstOrDefault(p => p.IsPrimary);
        var columns = entity.Properties; // value columns, declaration order
        var tableRef = new TableRef(schema, Table(entity, convention));
        var colNames = columns.Select(p => Col(p, convention)).ToList();

        // Value columns (declaration order) followed by a `<ref>_id` foreign-key column for each single
        // reference (FR-020): typed as the target entity's primary-key DormantQL type (the renderer maps it
        // per dialect), NOT NULL iff the ref is required. Reads materialize value columns only; the FK
        // column is written by commands, read via the relationship.
        var ddlColumns = columns
            .Select(p => new ColumnDef(Col(p, convention), p.DslType, !p.IsNullable, p.IsPrimary))
            .ToList();
        foreach (var reference in entity.References.Where(r => r.Kind == ReferenceKind.Ref))
        {
            var fkDslType = refPkDslTypes.TryGetValue(reference.TargetEntity, out var t)
                ? t
                : "uuid";
            ddlColumns.Add(
                new ColumnDef(
                    NamingConventions.Resolve(reference.Name, null, convention) + "_id",
                    fkDslType,
                    reference.IsRequired,
                    false
                )
            );
        }

        var createTable = new CreateTableStatement(tableRef, ddlColumns);

        var writer = new SourceWriter()
            .Line("// <auto-generated/>")
            .Line("#nullable enable")
            .Line()
            .Line($"namespace {@namespace};")
            .Line()
            .Open(
                $"internal sealed class {entity.Name}Binding : {Abs}.Entities.IEntityBinding<{entity.Name}>"
            )
            .Line("[global::System.Runtime.CompilerServices.ModuleInitializer]")
            .Line(
                $"internal static void Register() => {Abs}.Entities.EntityBindings.Register<{entity.Name}>(new {entity.Name}Binding());"
            )
            .Line()
            .Line($"public string Schema => {Quote(schema)};")
            .Line();

        EmitCreateSchemaSql(writer, new CreateSchemaStatement(schema));
        EmitCreateTableSql(writer, createTable);
        EmitMaterialize(writer, entity);
        EmitSelectByKey(writer, entity, tableRef, colNames, key, convention);

        return writer.Close().ToString();
    }

    private static string Table(EntityModel entity, NamingConvention convention) =>
        NamingConventions.Resolve(entity.Name, entity.NameOverride, convention);

    private static string Col(PropertyModel property, NamingConvention convention) =>
        NamingConventions.Resolve(property.Name, property.NameOverride, convention);

    private static void EmitCreateSchemaSql(SourceWriter writer, CreateSchemaStatement createSchema)
    {
        writer.Line($"public string CreateSchemaSql({DialectId} dialect) =>");
        DialectSwitch.WriteStatementArg(writer, "    ", "dialect", createSchema, ";");
        writer.Line();
    }

    private static void EmitCreateTableSql(SourceWriter writer, CreateTableStatement createTable)
    {
        writer.Line($"public string CreateTableSql({DialectId} dialect) =>");
        DialectSwitch.WriteStatementArg(writer, "    ", "dialect", createTable, ";");
        writer.Line();
    }

    private static void EmitMaterialize(SourceWriter writer, EntityModel entity)
    {
        // Delegates to the entity's generated ctor; reads value columns positionally in SELECT order.
        writer
            .Open($"public {entity.Name} Materialize({Abs}.Querying.IFieldReader reader)")
            .Line($"return new {entity.Name}(reader);")
            .Close()
            .Line();
    }

    private static void EmitSelectByKey(
        SourceWriter writer,
        EntityModel entity,
        TableRef table,
        IReadOnlyList<string> colNames,
        PropertyModel? key,
        NamingConvention convention
    )
    {
        writer.Open($"public {Stmt} SelectByKey({DialectId} dialect, object key)");
        if (key is null)
        {
            writer.Line(
                "throw new global::System.NotSupportedException(\"Entity has no single primary key.\");"
            );
        }
        else
        {
            var select = new SelectStatement(
                table,
                colNames,
                [new SqlCondition(Col(key, convention), "=", 1)],
                [],
                Limit: null,
                Offset: null
            );
            writer.Line($"return new {Stmt}(");
            DialectSwitch.WriteStatementArg(writer, "    ", "dialect", select, ",");
            writer.Line($"    writer => writer.Write(1, ({key.ClrType})key));");
        }

        writer.Close();
    }

    private static string Quote(string text) =>
        "\"" + text.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
