using Dormant.SourceGeneration.Emit;
using Dormant.SourceGeneration.Parsing;

namespace Dormant.SourceGeneration.Schema;

/// <summary>
/// Emits a strongly-typed <c>partial</c> entity class from an <see cref="EntityModel"/> (spec
/// FR-003): value properties as auto-properties and links as <c>Link&lt;T&gt;</c>/<c>LinkSet&lt;T&gt;</c>
/// members. Output is deterministic (source order, <c>\n</c> newlines, invariant formatting).
/// </summary>
internal static class EntityEmitter
{
    private const string LinkType = "global::Dormant.Abstractions.Links.Link";
    private const string LinkSetType = "global::Dormant.Abstractions.Links.LinkSet";

    public static string Emit(string moduleName, EntityModel entity)
    {
        var writer = new SourceWriter()
            .Line("// <auto-generated/>")
            .Line("#nullable enable")
            .Line()
            .Line($"namespace {moduleName};")
            .Line()
            .Open($"public partial class {entity.Name}");

        foreach (var property in entity.Properties)
        {
            var type = property.IsNullable ? property.ClrType + "?" : property.ClrType;
            var initializer = NeedsNullForgivingInitializer(property) ? " = default!;" : string.Empty;
            writer.Line($"public {type} {Naming.ToPascalCase(property.Name)} {{ get; set; }}{initializer}");
        }

        foreach (var link in entity.Links)
        {
            var wrapper = link.IsMulti ? LinkSetType : LinkType;
            writer.Line(
                $"public {wrapper}<{link.TargetEntity}> {Naming.ToPascalCase(link.Name)} {{ get; set; }}");
        }

        return writer.Close().ToString();
    }

    // Non-nullable reference-typed columns need a null-forgiving initializer to avoid CS8618 in the
    // consumer build; they are populated by the materializer (US2).
    private static bool NeedsNullForgivingInitializer(PropertyModel property) =>
        !property.IsNullable && property.ClrType is "string" or "byte[]";
}
