using System.Linq;
using Dormant.SourceGeneration.Emit;
using Dormant.SourceGeneration.Parsing;

namespace Dormant.SourceGeneration.Schema;

/// <summary>
/// Emits a strongly-typed <c>partial</c> entity class from an <see cref="EntityModel"/> (spec
/// FR-003/FR-046/FR-047/FR-048/FR-049/FR-051): value properties; relationship members typed
/// <c>Ref</c>/<c>RefSet</c>/<c>RefList</c>/<c>RefBag</c>/<c>RefMap</c> (collections default to the
/// Unloaded sentinel, never <c>[]</c>); the C# <c>required</c> modifier on non-nullable values and
/// required single refs; and primary-key identity <c>Equals</c>/<c>GetHashCode</c>. Output is
/// deterministic (source order, <c>\n</c> newlines, invariant formatting).
/// </summary>
internal static class EntityEmitter
{
    private const string Ns = "global::Dormant.Abstractions.Entities";

    public static string Emit(string @namespace, EntityModel entity)
    {
        var primaryKey = entity.Properties.FirstOrDefault(p => p.IsPrimary);
        var hasSinglePrimaryKey = primaryKey is not null
            && entity.Properties.Count(p => p.IsPrimary) == 1;

        var declaration = hasSinglePrimaryKey
            ? $"public partial class {entity.Name} : global::System.IEquatable<{entity.Name}>"
            : $"public partial class {entity.Name}";

        var writer = new SourceWriter()
            .Line("// <auto-generated/>")
            .Line("#nullable enable")
            .Line()
            .Line($"namespace {@namespace};")
            .Line()
            .Open(declaration);

        EmitConstructors(writer, entity);

        foreach (var property in entity.Properties)
        {
            var name = Naming.ToPascalCase(property.Name);
            if (property.IsNullable)
            {
                writer.Line($"public {property.ClrType}? {name} {{ get; set; }}");
            }
            else
            {
                writer.Line($"public required {property.ClrType} {name} {{ get; set; }}");
            }
        }

        foreach (var reference in entity.References)
        {
            EmitReference(writer, reference);
        }

        if (hasSinglePrimaryKey)
        {
            EmitIdentityEquality(writer, entity.Name, primaryKey!);
        }

        return writer.Close().ToString();
    }

    // Two constructors (FR-048): the public parameterless ctor preserves the consumer `required`-init
    // contract (`new E { ... }`); the internal `[SetsRequiredMembers]` ctor materializes a row by reading
    // value columns positionally through ordinary public setters — no reflection, no `[UnsafeAccessor]`,
    // no backing-field access. References are left at their default Unloaded sentinel (filled by US3
    // shapes / explicit load); `[SetsRequiredMembers]` lets required single refs stay Unloaded here.
    private static void EmitConstructors(SourceWriter writer, EntityModel entity)
    {
        writer
            .Line($"/// <summary>Initializes a new <see cref=\"{entity.Name}\"/> for `required`-init construction.</summary>")
            .Line($"public {entity.Name}() {{ }}")
            .Line();

        writer
            .Line("/// <summary>Materializes an instance from a data row (internal; used by the generated binding).</summary>")
            .Line("[global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]")
            .Open($"internal {entity.Name}(global::Dormant.Abstractions.Querying.IFieldReader reader)");

        var ordinal = 0;
        foreach (var property in entity.Properties)
        {
            var name = Naming.ToPascalCase(property.Name);
            var read = $"reader.GetValue<{property.ClrType}>({ordinal})";
            writer.Line(property.IsNullable
                ? $"this.{name} = reader.IsNull({ordinal}) ? null : {read};"
                : $"this.{name} = {read};");
            ordinal++;
        }

        writer.Close().Line();
    }

    private static void EmitReference(SourceWriter writer, ReferenceModel reference)
    {
        var name = Naming.ToPascalCase(reference.Name);
        var target = reference.TargetEntity;

        switch (reference.Kind)
        {
            case ReferenceKind.Ref when reference.IsRequired:
                writer.Line($"public required {Ns}.Ref<{target}> {name} {{ get; set; }}");
                break;
            case ReferenceKind.Ref:
                writer.Line($"public {Ns}.Ref<{target}?> {name} {{ get; set; }} = {Ns}.Ref<{target}?>.Unloaded;");
                break;
            case ReferenceKind.Set:
                writer.Line($"public {Ns}.RefSet<{target}> {name} {{ get; set; }} = {Ns}.RefSet<{target}>.Unloaded;");
                break;
            case ReferenceKind.List:
                writer.Line($"public {Ns}.RefList<{target}> {name} {{ get; set; }} = {Ns}.RefList<{target}>.Unloaded;");
                break;
            case ReferenceKind.Bag:
                writer.Line($"public {Ns}.RefBag<{target}> {name} {{ get; set; }} = {Ns}.RefBag<{target}>.Unloaded;");
                break;
            case ReferenceKind.Map:
                var keyClr = TypeMap.TryMap(reference.KeyType ?? string.Empty, out var mapped)
                    ? mapped
                    : reference.KeyType;
                writer.Line(
                    $"public {Ns}.RefMap<{keyClr}, {target}> {name} {{ get; set; }} = {Ns}.RefMap<{keyClr}, {target}>.Unloaded;");
                break;
        }
    }

    // Identity equality by primary key (FR-051): a transient (unset key) entity uses reference equality.
    private static void EmitIdentityEquality(SourceWriter writer, string entityName, PropertyModel key)
    {
        var keyName = Naming.ToPascalCase(key.Name);
        var cmp = $"global::System.Collections.Generic.EqualityComparer<{key.ClrType}>.Default";

        writer.Line()
            .Line($"/// <inheritdoc/>")
            .Open($"public bool Equals({entityName}? other)")
            .Line("if (other is null) { return false; }")
            .Line("if (object.ReferenceEquals(this, other)) { return true; }")
            .Line($"if ({cmp}.Equals(this.{keyName}, default!)) {{ return false; }}")
            .Line($"return {cmp}.Equals(this.{keyName}, other.{keyName});")
            .Close()
            .Line()
            .Line($"/// <inheritdoc/>")
            .Line($"public override bool Equals(object? obj) => this.Equals(obj as {entityName});")
            .Line()
            .Line($"/// <inheritdoc/>")
            .Open("public override int GetHashCode()")
            .Line($"return {cmp}.Equals(this.{keyName}, default!)")
            .Line($"    ? global::System.Runtime.CompilerServices.RuntimeHelpers.GetHashCode(this)")
            .Line($"    : this.{keyName}!.GetHashCode();")
            .Close();
    }
}
