using System.Globalization;
using System.Linq;
using Dormant.SourceGeneration.Emit;
using Dormant.SourceGeneration.Parsing;

namespace Dormant.SourceGeneration.Schema;

/// <summary>
/// Emits a per-entity <c>IEntityBinding&lt;TEntity&gt;</c> (registered via a <c>[ModuleInitializer]</c>):
/// no-reflection materialization that delegates to the entity's generated
/// <c>[SetsRequiredMembers]</c> constructor (no boxing, no <c>[UnsafeAccessor]</c>, no backing-field access
/// — FR-017/FR-019/FR-048) plus prebuilt INSERT and SELECT-by-primary-key statements with positional
/// parameters. Reads/writes go through public getters/setters. v1 slice maps **value columns only**;
/// reference (FK) columns are handled in a later slice.
/// </summary>
internal static class EntityBindingEmitter
{
    private const string Abs = "global::Dormant.Abstractions";

    public static string Emit(string @namespace, EntityModel entity)
    {
        var key = entity.Properties.FirstOrDefault(p => p.IsPrimary);
        var columns = entity.Properties; // value columns, declaration order
        var columnsSql = string.Join(", ", columns.Select(p => "\"" + p.Name + "\""));
        var placeholders = string.Join(
            ", ",
            columns.Select((_, i) => "$" + (i + 1).ToString(CultureInfo.InvariantCulture)));
        var insertSql = $"INSERT INTO \"{entity.Name}\" ({columnsSql}) VALUES ({placeholders})";

        var writer = new SourceWriter()
            .Line("// <auto-generated/>")
            .Line("#nullable enable")
            .Line()
            .Line($"namespace {@namespace};")
            .Line()
            .Open($"internal sealed class {entity.Name}Binding : {Abs}.Entities.IEntityBinding<{entity.Name}>")
            .Line("[global::System.Runtime.CompilerServices.ModuleInitializer]")
            .Line($"internal static void Register() => {Abs}.Entities.EntityBindings.Register<{entity.Name}>(new {entity.Name}Binding());")
            .Line();

        EmitMaterialize(writer, entity);
        EmitInsert(writer, entity, insertSql, columns);
        EmitSelectByKey(writer, entity, columnsSql, key);

        return writer.Close().ToString();
    }

    private static void EmitMaterialize(SourceWriter writer, EntityModel entity)
    {
        // Delegates to the entity's generated [SetsRequiredMembers] ctor (EntityEmitter); the ctor reads
        // value columns positionally in the same order as the SELECT below. No reflection/UnsafeAccessor.
        writer
            .Open($"public {entity.Name} Materialize({Abs}.Querying.IFieldReader reader)")
            .Line($"return new {entity.Name}(reader);")
            .Close()
            .Line();
    }

    private static void EmitInsert(SourceWriter writer, EntityModel entity, string insertSql, EquatableArray<PropertyModel> columns)
    {
        writer.Open($"public {Abs}.Querying.PreparedStatement Insert({entity.Name} entity)")
            .Line($"return new {Abs}.Querying.PreparedStatement(")
            .Line($"    {Quote(insertSql)},")
            .Line("    writer =>")
            .Line("    {");

        var index = 1;
        foreach (var property in columns)
        {
            writer.Line($"        writer.Write({index}, entity.{Naming.ToPascalCase(property.Name)});");
            index++;
        }

        writer.Line("    });").Close().Line();
    }

    private static void EmitSelectByKey(SourceWriter writer, EntityModel entity, string columnsSql, PropertyModel? key)
    {
        writer.Open("public " + Abs + ".Querying.PreparedStatement SelectByKey(object key)");
        if (key is null)
        {
            writer.Line("throw new global::System.NotSupportedException(\"Entity has no single primary key.\");");
        }
        else
        {
            var selectSql = $"SELECT {columnsSql} FROM \"{entity.Name}\" WHERE \"{key.Name}\" = $1";
            writer
                .Line($"return new {Abs}.Querying.PreparedStatement(")
                .Line($"    {Quote(selectSql)},")
                .Line($"    writer => writer.Write(1, ({key.ClrType})key));");
        }

        writer.Close();
    }

    // Renders a C# double-quoted string literal for the given text.
    private static string Quote(string text) =>
        "\"" + text.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
