using Dormant.SourceGeneration.Emit;
using Dormant.SourceGeneration.Parsing;

namespace Dormant.SourceGeneration.Schema;

/// <summary>
/// Emits a per-entity materializer that builds an instance from an <c>IFieldReader</c> with **no
/// reflection** (spec FR-017/FR-019, research §10): a private parameterless constructor is invoked
/// through <c>[UnsafeAccessor]</c> (bypassing C# <c>required</c>-init enforcement, FR-048) and each
/// mapped value column is written into the auto-property backing field via an <c>[UnsafeAccessor]</c>
/// field accessor (no boxing). Value columns are read in declaration order (ordinals 0..n); references
/// are left Unloaded (the constructor runs their Unloaded initializers).
/// </summary>
internal static class MaterializerEmitter
{
    private const string Uac = "global::System.Runtime.CompilerServices.UnsafeAccessor";
    private const string UacKind = "global::System.Runtime.CompilerServices.UnsafeAccessorKind";
    private const string FieldReader = "global::Dormant.Abstractions.Querying.IFieldReader";

    public static string Emit(string @namespace, EntityModel entity)
    {
        var writer = new SourceWriter()
            .Line("// <auto-generated/>")
            .Line("#nullable enable")
            .Line()
            .Line($"namespace {@namespace};")
            .Line()
            .Open($"internal static class {entity.Name}Materialization")
            .Line($"[{Uac}({UacKind}.Constructor)]")
            .Line($"private static extern {entity.Name} Create();")
            .Line();

        var ordinal = 0;
        foreach (var property in entity.Properties)
        {
            var fieldType = property.IsNullable ? property.ClrType + "?" : property.ClrType;
            var name = Naming.ToPascalCase(property.Name);
            writer
                .Line($"[{Uac}({UacKind}.Field, Name = \"<{name}>k__BackingField\")]")
                .Line($"private static extern ref {fieldType} {name}Field({entity.Name} entity);")
                .Line();
            ordinal++;
        }

        writer.Open($"public static {entity.Name} Materialize({FieldReader} reader)")
            .Line($"var entity = Create();");

        ordinal = 0;
        foreach (var property in entity.Properties)
        {
            var name = Naming.ToPascalCase(property.Name);
            var read = $"reader.GetValue<{property.ClrType}>({ordinal})";
            var assignment = property.IsNullable
                ? $"reader.IsNull({ordinal}) ? null : {read}"
                : read;
            writer.Line($"{name}Field(entity) = {assignment};");
            ordinal++;
        }

        return writer
            .Line("return entity;")
            .Close()
            .Close()
            .ToString();
    }
}
