using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using Dormant.SourceGeneration.Diagnostics;
using Dormant.SourceGeneration.Emit;
using Dormant.SourceGeneration.Parsing;

namespace Dormant.SourceGeneration.Command;

/// <summary>
/// Emits, per DormantQL command file, a <c>partial static</c> <c>{Module}Commands</c> class of extension
/// methods on <c>ISession</c> (one per authored command), each carrying build-time SQL on a
/// <c>CompiledCommand&lt;T&gt;</c> (FR-002/FR-005). v1 MVP: <c>insert Entity { col := expr }</c> →
/// <c>INSERT … VALUES … RETURNING …</c>, materializing the inserted row via the entity's generated ctor.
/// Database names are schema-qualified + convention-resolved (carried from 001). Nested writes / CTEs +
/// update/delete arrive in later slices. Semantic errors are ORM010/011/012; the offending command is
/// skipped while valid siblings still emit.
/// </summary>
internal static class CommandEmitter
{
    private const string Abs = "global::Dormant.Abstractions";

    public static (string? Source, IReadOnlyList<DiagnosticInfo> Diagnostics) Emit(
        string @namespace,
        CommandFile file,
        IReadOnlyDictionary<string, (EntityModel Entity, string Schema)> entities,
        NamingConvention convention)
    {
        var diagnostics = new List<DiagnosticInfo>();
        var bodies = new List<string>();

        foreach (var command in file.Commands)
        {
            if (!entities.TryGetValue(command.RootEntity, out var entry))
            {
                diagnostics.Add(Diag(DiagnosticDescriptors.UnknownQueryEntity, file.FilePath, command.Name, command.RootEntity));
                continue;
            }

            if (!Validate(command, entry.Entity, file.FilePath, diagnostics))
            {
                continue;
            }

            bodies.Add(EmitMethod(command, entry.Entity, entry.Schema, convention));
        }

        if (bodies.Count == 0)
        {
            return (null, diagnostics);
        }

        var className = Naming.ToPascalCase(file.ModuleName) + "Commands";
        var writer = new SourceWriter()
            .Line("// <auto-generated/>")
            .Line("#nullable enable")
            .Line()
            .Line($"namespace {@namespace};")
            .Line()
            .Open($"public static partial class {className}")
            .Open($"extension({Abs}.Sessions.ISession session)");

        foreach (var body in bodies)
        {
            foreach (var line in body.Split('\n'))
            {
                writer.Line(line);
            }
        }

        writer.Close().Close().Line();
        return (writer.ToString(), diagnostics);
    }

    private static bool Validate(CommandModel command, EntityModel entity, string filePath, List<DiagnosticInfo> diagnostics)
    {
        var ok = true;
        var columns = new HashSet<string>(entity.Properties.Select(p => p.Name), System.StringComparer.Ordinal);
        var parameters = new HashSet<string>(command.Parameters.Select(p => p.Name), System.StringComparer.Ordinal);

        foreach (var assignment in command.Assignments)
        {
            if (!columns.Contains(assignment.Column))
            {
                diagnostics.Add(Diag(DiagnosticDescriptors.UnknownQueryColumn, filePath, command.Name, assignment.Column, entity.Name));
                ok = false;
            }

            if (assignment.Value.Kind == CommandValueKind.Parameter && !parameters.Contains(assignment.Value.Text))
            {
                diagnostics.Add(Diag(DiagnosticDescriptors.UnknownQueryParameter, filePath, command.Name, assignment.Value.Text));
                ok = false;
            }
        }

        return ok;
    }

    private static string EmitMethod(CommandModel command, EntityModel entity, string schema, NamingConvention convention)
    {
        var table = "\"" + schema + "\".\"" + NamingConventions.Resolve(entity.Name, entity.NameOverride, convention) + "\"";

        // Build the assigned-columns + value tokens; param/literal → $n (bound), native → inline SQL.
        var assignedColumns = new List<string>();
        var valueTokens = new List<string>();
        var binds = new List<string>(); // generated bind statements, in $n order
        var p = 0;
        foreach (var assignment in command.Assignments)
        {
            var property = entity.Properties.First(x => x.Name == assignment.Column);
            assignedColumns.Add("\"" + NamingConventions.Resolve(property.Name, property.NameOverride, convention) + "\"");

            switch (assignment.Value.Kind)
            {
                case CommandValueKind.Parameter:
                    p++;
                    valueTokens.Add("$" + p.ToString(CultureInfo.InvariantCulture));
                    binds.Add($"writer.Write({p}, {assignment.Value.Text});");
                    break;
                case CommandValueKind.StringLiteral:
                    p++;
                    valueTokens.Add("$" + p.ToString(CultureInfo.InvariantCulture));
                    binds.Add($"writer.Write({p}, {Quote(assignment.Value.Text)});");
                    break;
                case CommandValueKind.NumberLiteral:
                    p++;
                    valueTokens.Add("$" + p.ToString(CultureInfo.InvariantCulture));
                    binds.Add($"writer.Write({p}, {assignment.Value.Text});");
                    break;
                case CommandValueKind.NativeCall:
                    valueTokens.Add(NativeSql(assignment.Value.Text));
                    break;
            }
        }

        var returning = string.Join(
            ", ",
            entity.Properties.Select(x => "\"" + NamingConventions.Resolve(x.Name, x.NameOverride, convention) + "\""));
        var sql = $"INSERT INTO {table} ({string.Join(", ", assignedColumns)}) VALUES ({string.Join(", ", valueTokens)}) RETURNING {returning}";

        var declared = string.Join(", ", command.Parameters.Select(x => $"{x.ClrType} {x.Name}"));
        var parameterList = declared.Length > 0 ? declared + ", " : string.Empty;

        var w = new SourceWriter()
            .Open($"public async global::System.Threading.Tasks.ValueTask<{entity.Name}> {command.Name}({parameterList}global::System.Threading.CancellationToken cancellationToken = default)")
            .Line($"var statement = new {Abs}.Querying.PreparedStatement(")
            .Line($"    {Quote(sql)},")
            .Line("    writer =>")
            .Line("    {");

        foreach (var bind in binds)
        {
            w.Line("        " + bind);
        }

        w
            .Line("    });")
            .Line($"var command = new {Abs}.Querying.CompiledCommand<{entity.Name}>(statement, static reader => new {entity.Name}(reader));")
            .Line("return await session.ExecuteCommandAsync(command, cancellationToken).ConfigureAwait(false);")
            .Close();

        return w.ToString().TrimEnd('\n');
    }

    // Maps a v1 native function to its PostgreSQL SQL. Minimal: datetime::now() → now().
    private static string NativeSql(string func) => func switch
    {
        "now" => "now()",
        _ => func + "()",
    };

    private static string Quote(string text) =>
        "\"" + text.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    private static DiagnosticInfo Diag(
        Microsoft.CodeAnalysis.DiagnosticDescriptor descriptor,
        string filePath,
        params string[] args) =>
        new(descriptor, new LocationInfo(filePath, default, default), new EquatableArray<string>(args));
}
