using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using Dormant.SourceGeneration.Diagnostics;
using Dormant.SourceGeneration.Emit;
using Dormant.SourceGeneration.Ir;
using Dormant.SourceGeneration.Parsing;

namespace Dormant.SourceGeneration.Command;

/// <summary>
/// Emits, per DormantQL command file, a <c>partial static</c> <c>{Module}Commands</c> class of extension
/// methods on <c>ISession</c> (one per authored command), each carrying build-time SQL on a
/// <c>CompiledCommand&lt;T&gt;</c> (FR-002/FR-005). v1 MVP: <c>insert Entity { col := expr }</c> →
/// <c>INSERT … VALUES … RETURNING …</c>, materializing the inserted row via the entity's generated ctor.
/// Database names are schema-qualified + convention-resolved (carried from 001). Nested writes / CTEs +
/// update/delete arrive in later slices. Semantic errors are ORM010/011/012; the offending command is
/// skipped while valid siblings still emit.
/// </summary>
internal static class CommandEmitter
{
    private const string Abs = "global::Dormant.Abstractions";

    public static (string? Source, IReadOnlyList<DiagnosticInfo> Diagnostics) Emit(
        string @namespace,
        CommandFile file,
        IReadOnlyDictionary<string, (EntityModel Entity, string Schema)> entities,
        NamingConvention convention)
    {
        var diagnostics = new List<DiagnosticInfo>();
        var bodies = new List<string>();

        foreach (var command in file.Commands)
        {
            if (!entities.TryGetValue(command.RootEntity, out var entry))
            {
                diagnostics.Add(Diag(DiagnosticDescriptors.UnknownQueryEntity, file.FilePath, command.Name, command.RootEntity));
                continue;
            }

            if (!Validate(command, entry.Entity, file.FilePath, diagnostics))
            {
                continue;
            }

            bodies.Add(EmitMethod(command, entry.Entity, entry.Schema, convention));
        }

        if (bodies.Count == 0)
        {
            return (null, diagnostics);
        }

        var className = Naming.ToPascalCase(file.ModuleName) + "Commands";
        var writer = new SourceWriter()
            .Line("// <auto-generated/>")
            .Line("#nullable enable")
            .Line()
            .Line($"namespace {@namespace};")
            .Line()
            .Open($"public static partial class {className}")
            .Open($"extension({Abs}.Sessions.ISession session)");

        foreach (var body in bodies)
        {
            foreach (var line in body.Split('\n'))
            {
                writer.Line(line);
            }
        }

        writer.Close().Close().Line();
        return (writer.ToString(), diagnostics);
    }

    private static bool Validate(CommandModel command, EntityModel entity, string filePath, List<DiagnosticInfo> diagnostics)
    {
        var ok = true;
        var columns = new HashSet<string>(entity.Properties.Select(p => p.Name), System.StringComparer.Ordinal);
        var parameters = new HashSet<string>(command.Parameters.Select(p => p.Name), System.StringComparer.Ordinal);

        foreach (var assignment in command.Assignments)
        {
            if (!columns.Contains(assignment.Column))
            {
                diagnostics.Add(Diag(DiagnosticDescriptors.UnknownQueryColumn, filePath, command.Name, assignment.Column, entity.Name));
                ok = false;
            }

            if (assignment.Value.Kind == CommandValueKind.Parameter && !parameters.Contains(assignment.Value.Text))
            {
                diagnostics.Add(Diag(DiagnosticDescriptors.UnknownQueryParameter, filePath, command.Name, assignment.Value.Text));
                ok = false;
            }
        }

        foreach (var filter in command.Filters)
        {
            if (!columns.Contains(filter.Column))
            {
                diagnostics.Add(Diag(DiagnosticDescriptors.UnknownQueryColumn, filePath, command.Name, filter.Column, entity.Name));
                ok = false;
            }

            if (!parameters.Contains(filter.ParameterName))
            {
                diagnostics.Add(Diag(DiagnosticDescriptors.UnknownQueryParameter, filePath, command.Name, filter.ParameterName));
                ok = false;
            }
        }

        return ok;
    }

    private static string EmitMethod(CommandModel command, EntityModel entity, string schema, NamingConvention convention) =>
        command.Kind switch
        {
            CommandKind.Insert => EmitInsert(command, entity, schema, convention),
            CommandKind.Update => EmitUpdate(command, entity, schema, convention),
            CommandKind.Delete => EmitDelete(command, entity, schema, convention),
            _ => throw new System.NotSupportedException($"Unknown command kind: {command.Kind}"),
        };

    private static string EmitInsert(CommandModel command, EntityModel entity, string schema, NamingConvention convention)
    {
        var table = new TableRef(schema, Col(entity.Name, entity.NameOverride, convention));
        var binds = new List<string>();
        var p = 0;
        var assignedColumns = new List<InsertColumn>();
        var valueTokens = new List<string>();
        foreach (var assignment in command.Assignments)
        {
            var property = entity.Properties.First(x => x.Name == assignment.Column);
            assignedColumns.Add(new InsertColumn(Col(property.Name, property.NameOverride, convention), null));
            valueTokens.Add(ValueToken(assignment.Value, property, ref p, binds));
        }

        var columns = string.Join(", ", assignedColumns.Select(c => "\"" + c.Name + "\""));
        var returning = string.Join(", ", entity.Properties.Select(x => "\"" + Col(x.Name, x.NameOverride, convention) + "\""));
        var sql = $"INSERT INTO {QualifiedTable(table)} ({columns}) VALUES ({string.Join(", ", valueTokens)}) RETURNING {returning}";

        var w = OpenMethod(command, $"global::System.Threading.Tasks.ValueTask<{entity.Name}>");
        EmitStatement(w, sql, binds);
        w
            .Line($"var command = new {Abs}.Querying.CompiledCommand<{entity.Name}>(statement, static reader => new {entity.Name}(reader));")
            .Line("return await session.ExecuteCommandAsync(command, cancellationToken).ConfigureAwait(false);")
            .Close();
        return w.ToString().TrimEnd('\n');
    }

    private static string EmitUpdate(CommandModel command, EntityModel entity, string schema, NamingConvention convention)
    {
        var table = new TableRef(schema, Col(entity.Name, entity.NameOverride, convention));
        var binds = new List<string>();
        var p = 0;
        var assignments = new List<SqlAssignment>();
        foreach (var assignment in command.Assignments)
        {
            var property = entity.Properties.First(x => x.Name == assignment.Column);
            assignments.Add(new SqlAssignment(Col(property.Name, property.NameOverride, convention), ValueToken(assignment.Value, property, ref p, binds)));
        }

        var where = BuildWhere(command, entity, convention, ref p, binds);
        var sql = SqlRenderer.Render(new UpdateStatement(table, assignments, where));
        return EmitWriteMethod(command, sql, binds);
    }

    private static string EmitDelete(CommandModel command, EntityModel entity, string schema, NamingConvention convention)
    {
        var table = new TableRef(schema, Col(entity.Name, entity.NameOverride, convention));
        var binds = new List<string>();
        var p = 0;
        var where = BuildWhere(command, entity, convention, ref p, binds);
        var sql = SqlRenderer.Render(new DeleteStatement(table, where));
        return EmitWriteMethod(command, sql, binds);
    }

    // A value token for an assignment: param/literal → $n (bound, +`::jsonb` for json), native → inline SQL.
    private static string ValueToken(CommandValue value, PropertyModel property, ref int p, List<string> binds)
    {
        var cast = property.DslType == "json" ? "::jsonb" : string.Empty;
        switch (value.Kind)
        {
            case CommandValueKind.Parameter:
                p++;
                binds.Add($"writer.Write({p}, {value.Text});");
                return "$" + p.ToString(CultureInfo.InvariantCulture) + cast;
            case CommandValueKind.StringLiteral:
                p++;
                binds.Add($"writer.Write({p}, {Quote(value.Text)});");
                return "$" + p.ToString(CultureInfo.InvariantCulture) + cast;
            case CommandValueKind.NumberLiteral:
                p++;
                binds.Add($"writer.Write({p}, {value.Text});");
                return "$" + p.ToString(CultureInfo.InvariantCulture) + cast;
            default: // NativeCall
                return NativeSql(value.Text);
        }
    }

    private static List<SqlCondition> BuildWhere(CommandModel command, EntityModel entity, NamingConvention convention, ref int p, List<string> binds)
    {
        var where = new List<SqlCondition>(command.Filters.Count);
        foreach (var filter in command.Filters)
        {
            var property = entity.Properties.First(x => x.Name == filter.Column);
            p++;
            where.Add(new SqlCondition(Col(property.Name, property.NameOverride, convention), OperatorSql(filter.Op), p));
            binds.Add($"writer.Write({p}, {filter.ParameterName});");
        }

        return where;
    }

    private static SourceWriter OpenMethod(CommandModel command, string returnType)
    {
        // 003: the authored snake_case unit name becomes a PascalCase C# method.
        var methodName = Naming.ToPascalCase(command.Name);
        var declared = string.Join(", ", command.Parameters.Select(x => $"{x.ClrType} {x.Name}"));
        var parameterList = declared.Length > 0 ? declared + ", " : string.Empty;
        return new SourceWriter()
            .Open($"public async {returnType} {methodName}({parameterList}global::System.Threading.CancellationToken cancellationToken = default)");
    }

    private static void EmitStatement(SourceWriter w, string sql, List<string> binds)
    {
        w
            .Line($"var statement = new {Abs}.Querying.PreparedStatement(")
            .Line($"    {Quote(sql)},")
            .Line("    writer =>")
            .Line("    {");
        foreach (var bind in binds)
        {
            w.Line("        " + bind);
        }

        w.Line("    });");
    }

    // update/delete return the affected-row count (0 on a stale concurrency token → caller's conflict).
    private static string EmitWriteMethod(CommandModel command, string sql, List<string> binds)
    {
        var w = OpenMethod(command, "global::System.Threading.Tasks.ValueTask<int>");
        EmitStatement(w, sql, binds);
        w.Line("return await session.ExecuteWriteAsync(statement, cancellationToken).ConfigureAwait(false);").Close();
        return w.ToString().TrimEnd('\n');
    }

    private static string QualifiedTable(TableRef table) =>
        table.Schema is null ? "\"" + table.Name + "\"" : "\"" + table.Schema + "\".\"" + table.Name + "\"";

    private static string Col(string name, string? nameOverride, NamingConvention convention) =>
        NamingConventions.Resolve(name, nameOverride, convention);

    private static string OperatorSql(CompareOp op) => op switch
    {
        CompareOp.Eq => "=",
        CompareOp.Neq => "<>",
        CompareOp.Lt => "<",
        CompareOp.Gt => ">",
        CompareOp.Le => "<=",
        CompareOp.Ge => ">=",
        CompareOp.Like => "LIKE",
        CompareOp.ILike => "ILIKE",
        _ => "=",
    };

    // Maps a v1 native function to its PostgreSQL SQL. Minimal: datetime::now() → now().
    private static string NativeSql(string func) => func switch
    {
        "now" => "now()",
        _ => func + "()",
    };

    private static string Quote(string text) =>
        "\"" + text.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    private static DiagnosticInfo Diag(
        Microsoft.CodeAnalysis.DiagnosticDescriptor descriptor,
        string filePath,
        params string[] args) =>
        new(descriptor, new LocationInfo(filePath, default, default), new EquatableArray<string>(args));
}
