using System.Collections.Generic;
using System.Linq;
using Dormant.SourceGeneration.Diagnostics;
using Dormant.SourceGeneration.Emit;
using Dormant.SourceGeneration.Ir;
using Dormant.SourceGeneration.Ir.Dialects;
using Dormant.SourceGeneration.Parsing;

namespace Dormant.SourceGeneration.Command;

/// <summary>
/// Emits, per DormantQL command file, a <c>partial static</c> <c>{Module}Commands</c> class of extension
/// methods on <c>ISession</c> (one per authored command), each carrying build-time SQL on a
/// <c>CompiledCommand&lt;T&gt;</c> (FR-002/FR-005). The SQL is emitted as a per-dialect variant switch keyed
/// by <c>session.Dialect</c> (005 D3); the parameter binder is dialect-neutral (positional add order).
/// Database names are schema-qualified + convention-resolved. Semantic errors are ORM010/011/012; the
/// offending command is skipped while valid siblings still emit.
/// </summary>
internal static class CommandEmitter
{
    private const string Abs = "global::Dormant.Abstractions";

    public static (string? Source, IReadOnlyList<DiagnosticInfo> Diagnostics) Emit(
        string @namespace,
        CommandFile file,
        IReadOnlyDictionary<string, (EntityModel Entity, string Schema)> entities,
        NamingConvention convention)
    {
        var diagnostics = new List<DiagnosticInfo>();
        var bodies = new List<string>();
        var projections = new List<string>();

        foreach (var command in file.Commands)
        {
            if (!entities.TryGetValue(command.RootEntity, out var entry))
            {
                diagnostics.Add(Diag(DiagnosticDescriptors.UnknownQueryEntity, file.FilePath, command.Name, command.RootEntity));
                continue;
            }

            if (!Validate(command, entry.Entity, file.FilePath, diagnostics))
            {
                continue;
            }

            // Validate each `with` binding's command against its (possibly different) entity (FR-021/FR-022).
            var bindingsOk = true;
            foreach (var binding in command.Bindings)
            {
                if (!entities.TryGetValue(binding.Command.RootEntity, out var bentry))
                {
                    diagnostics.Add(Diag(DiagnosticDescriptors.UnknownQueryEntity, file.FilePath, command.Name, binding.Command.RootEntity));
                    bindingsOk = false;
                    continue;
                }

                if (!Validate(binding.Command, bentry.Entity, file.FilePath, diagnostics))
                {
                    bindingsOk = false;
                }
            }

            if (!bindingsOk)
            {
                continue;
            }

            bodies.Add(EmitMethod(command, entry.Entity, entry.Schema, convention, entities, out var projection));
            if (projection is not null)
            {
                projections.Add(projection);
            }
        }

        if (bodies.Count == 0)
        {
            return (null, diagnostics);
        }

        var className = Naming.ToPascalCase(file.ModuleName) + "Commands";
        var writer = new SourceWriter()
            .Line("// <auto-generated/>")
            .Line("#nullable enable")
            .Line()
            .Line($"namespace {@namespace};")
            .Line()
            .Open($"public static partial class {className}")
            .Open($"extension({Abs}.Sessions.ISession session)");

        foreach (var body in bodies)
        {
            foreach (var line in body.Split('\n'))
            {
                writer.Line(line);
            }
        }

        writer.Close().Close().Line();

        foreach (var projection in projections)
        {
            writer.Line(projection);
        }

        return (writer.ToString(), diagnostics);
    }

    private static bool Validate(CommandModel command, EntityModel entity, string filePath, List<DiagnosticInfo> diagnostics)
    {
        var ok = true;
        var columns = new HashSet<string>(entity.Properties.Select(p => p.Name), System.StringComparer.Ordinal);
        var parameters = new HashSet<string>(command.Parameters.Select(p => p.Name), System.StringComparer.Ordinal);
        // FR-020/021: an assignment target may be a value property OR a single reference (`alias.ref = expr`
        // writes the `<ref>_id` FK column).
        var singleRefs = new HashSet<string>(
            entity.References.Where(r => r.Kind == ReferenceKind.Ref).Select(r => r.Name), System.StringComparer.Ordinal);

        foreach (var assignment in command.Assignments)
        {
            if (!columns.Contains(assignment.Column) && !singleRefs.Contains(assignment.Column))
            {
                diagnostics.Add(Diag(DiagnosticDescriptors.UnknownQueryColumn, filePath, command.Name, assignment.Column, entity.Name));
                ok = false;
            }

            if (assignment.Value.Kind == CommandValueKind.Parameter && !parameters.Contains(assignment.Value.Text))
            {
                diagnostics.Add(Diag(DiagnosticDescriptors.UnknownQueryParameter, filePath, command.Name, assignment.Value.Text));
                ok = false;
            }
        }

        foreach (var filter in command.Filters)
        {
            if (!columns.Contains(filter.Column))
            {
                diagnostics.Add(Diag(DiagnosticDescriptors.UnknownQueryColumn, filePath, command.Name, filter.Column, entity.Name));
                ok = false;
            }

            if (!parameters.Contains(filter.ParameterName))
            {
                diagnostics.Add(Diag(DiagnosticDescriptors.UnknownQueryParameter, filePath, command.Name, filter.ParameterName));
                ok = false;
            }
        }

        if (command.Returning is { } returning)
        {
            foreach (var member in returning.Members)
            {
                if (!columns.Contains(member))
                {
                    diagnostics.Add(Diag(DiagnosticDescriptors.UnknownQueryColumn, filePath, command.Name, member, entity.Name));
                    ok = false;
                }
            }
        }

        return ok;
    }

    private static string EmitMethod(
        CommandModel command,
        EntityModel entity,
        string schema,
        NamingConvention convention,
        IReadOnlyDictionary<string, (EntityModel Entity, string Schema)> entities,
        out string? projection)
    {
        // 003 (FR-021/FR-022): a `with`-block mutation runs each binding as its own statement (locals) then
        // the terminal command, all within the session transaction.
        if (command.Bindings.Count > 0)
        {
            return EmitWithBlock(command, entities, convention, out projection);
        }

        projection = null;
        return command.Kind switch
        {
            CommandKind.Insert => EmitInsert(command, entity, schema, convention, out projection),
            CommandKind.Update => EmitUpdate(command, entity, schema, convention, out projection),
            CommandKind.Delete => EmitDelete(command, entity, schema, convention, out projection),
            _ => throw new System.NotSupportedException($"Unknown command kind: {command.Kind}"),
        };
    }

    // Result shape → (CLR type, materializer expression, optional projection record source). Shared by the
    // with-block emitter (and mirrors EmitShapedMethod's single-command shaping).
    private static (string Clr, string Materializer, string? Projection) ShapeResult(
        ReturningShape shape, EntityModel entity, string methodName)
    {
        if (shape.Kind == ReturningKind.Scalar)
        {
            var prop = entity.Properties.First(x => x.Name == shape.Members[0]);
            var clr = prop.IsNullable ? prop.ClrType + "?" : prop.ClrType;
            var read = prop.IsNullable
                ? $"reader.IsNull(0) ? null : reader.GetValue<{prop.ClrType}>(0)"
                : $"reader.GetValue<{prop.ClrType}>(0)";
            return (clr, $"static reader => {read}", null);
        }

        if (shape.Kind == ReturningKind.Projection)
        {
            var resultType = methodName + "Result";
            var members = shape.Members.ToArray();
            var fields = members.Select(m =>
            {
                var prop = entity.Properties.First(x => x.Name == m);
                var clr = prop.IsNullable ? prop.ClrType + "?" : prop.ClrType;
                return $"{clr} {Naming.ToPascalCase(m)}";
            });
            var args = members.Select((m, i) =>
            {
                var prop = entity.Properties.First(x => x.Name == m);
                var read = $"reader.GetValue<{prop.ClrType}>({i})";
                return prop.IsNullable ? $"reader.IsNull({i}) ? null : {read}" : read;
            });
            return (
                resultType,
                $"static reader => new {resultType}({string.Join(", ", args)})",
                $"public sealed record {resultType}({string.Join(", ", fields)});");
        }

        return (entity.Name, $"static reader => new {entity.Name}(reader)", null);
    }

    // Builds the statement IR + bind statements for one command under a result shape (null shape on
    // update/delete ⇒ affected-count, no RETURNING). Reuses the single-command building blocks.
    private static SqlStatement BuildStatement(
        CommandModel cmd, EntityModel entity, string schema, NamingConvention convention, ReturningShape? shape, out List<string> binds)
    {
        binds = new List<string>();
        var p = 0;
        var table = new TableRef(schema, Col(entity.Name, entity.NameOverride, convention));

        if (cmd.Kind == CommandKind.Insert)
        {
            var cols = new List<string>();
            var values = new List<SqlValue>();
            foreach (var assignment in cmd.Assignments)
            {
                var (col, value) = ResolveAssignment(assignment, entity, convention, ref p, binds);
                cols.Add(col);
                values.Add(value);
            }

            var insertShape = shape ?? new ReturningShape(ReturningKind.Entity, new EquatableArray<string>([]));
            return new InsertStatement(table, cols, values, ReturningColumns(insertShape, entity, convention));
        }

        if (cmd.Kind == CommandKind.Update)
        {
            var assigns = new List<SqlAssignment>();
            foreach (var assignment in cmd.Assignments)
            {
                var (col, value) = ResolveAssignment(assignment, entity, convention, ref p, binds);
                assigns.Add(new SqlAssignment(col, value));
            }

            var where = BuildWhere(cmd, entity, convention, ref p, binds);
            return new UpdateStatement(table, assigns, where, shape is null ? null : ReturningColumns(shape, entity, convention));
        }

        var deleteWhere = BuildWhere(cmd, entity, convention, ref p, binds);
        return new DeleteStatement(table, deleteWhere, shape is null ? null : ReturningColumns(shape, entity, convention));
    }

    // Emits, inside an already-open method, one command as a uniquely-named PreparedStatement + its execution,
    // either to a local (`with` binding) or as the method's `return` (terminal). FR-022 sequence step.
    private static void EmitCommandStep(
        SourceWriter w, string suffix, SqlStatement statement, List<string> binds, string clr, string? materializer, bool isCount, string? local)
    {
        var stmtVar = "statement" + suffix;
        WriteStatement(w, stmtVar, statement, binds);

        string call;
        if (isCount)
        {
            call = $"await session.ExecuteWriteAsync({stmtVar}, cancellationToken).ConfigureAwait(false)";
        }
        else
        {
            var cmdVar = "command" + suffix;
            w.Line($"var {cmdVar} = new {Abs}.Querying.CompiledCommand<{clr}>({stmtVar}, {materializer});");
            call = $"await session.ExecuteCommandAsync({cmdVar}, cancellationToken).ConfigureAwait(false)";
        }

        w.Line(local is null ? $"return {call};" : $"var {local} = {call};");
    }

    // 003 FR-021/FR-022: a `with`-block mutation — each binding runs as its own statement (result → C# local),
    // then the terminal command produces the unit result; all in the session transaction (provider-portable,
    // no CTE). `with`-bound names flow into later commands as locals (e.g. a parent id into a child FK).
    private static string EmitWithBlock(
        CommandModel terminal, IReadOnlyDictionary<string, (EntityModel Entity, string Schema)> entities, NamingConvention convention, out string? projection)
    {
        projection = null;
        var methodName = Naming.ToPascalCase(terminal.Name);

        var terminalIsCount = terminal.Kind != CommandKind.Insert && terminal.Returning is null;
        ReturningShape? terminalShape = terminalIsCount
            ? null
            : terminal.Returning ?? new ReturningShape(ReturningKind.Entity, new EquatableArray<string>([]));

        var terminalEntry = entities[terminal.RootEntity];
        string terminalClr = "int";
        string? terminalMat = null;
        if (!terminalIsCount)
        {
            var (clr, mat, proj) = ShapeResult(terminalShape!, terminalEntry.Entity, methodName);
            terminalClr = clr;
            terminalMat = mat;
            projection = proj;
        }

        var w = OpenMethod(terminal, $"global::System.Threading.Tasks.ValueTask<{terminalClr}>");

        foreach (var binding in terminal.Bindings)
        {
            var bcmd = binding.Command;
            var bentry = entities[bcmd.RootEntity];
            var bIsCount = bcmd.Kind != CommandKind.Insert && bcmd.Returning is null;

            // A binding's default shape is the inserted PK (a scalar) so the local is usable as a FK; an
            // explicit `returning` overrides; update/delete without returning yields the affected count.
            ReturningShape? bshape;
            if (bIsCount)
            {
                bshape = null;
            }
            else if (bcmd.Returning is not null)
            {
                bshape = bcmd.Returning;
            }
            else
            {
                var pk = bentry.Entity.Properties.First(x => x.IsPrimary);
                bshape = new ReturningShape(ReturningKind.Scalar, new EquatableArray<string>([pk.Name]));
            }

            var bstmt = BuildStatement(bcmd, bentry.Entity, bentry.Schema, convention, bshape, out var bbinds);
            string bclr = "int";
            string? bmat = null;
            if (!bIsCount)
            {
                var (clr, mat, _) = ShapeResult(bshape!, bentry.Entity, methodName + "_" + binding.Name);
                bclr = clr;
                bmat = mat;
            }

            EmitCommandStep(w, "_" + binding.Name, bstmt, bbinds, bclr, bmat, bIsCount, binding.Name);
        }

        var tstmt = BuildStatement(terminal, terminalEntry.Entity, terminalEntry.Schema, convention, terminalShape, out var tbinds);
        EmitCommandStep(w, string.Empty, tstmt, tbinds, terminalClr, terminalMat, terminalIsCount, local: null);

        w.Close();
        return w.ToString().TrimEnd('\n');
    }

    private static string EmitInsert(CommandModel command, EntityModel entity, string schema, NamingConvention convention, out string? projection)
    {
        // insert always materializes a result; the default shape is the full entity (`returning alias`).
        var shape = command.Returning ?? new ReturningShape(ReturningKind.Entity, new EquatableArray<string>([]));
        var statement = BuildStatement(command, entity, schema, convention, shape, out var binds);
        return EmitShapedMethod(command, entity, shape, statement, binds, out projection);
    }

    private static string EmitUpdate(CommandModel command, EntityModel entity, string schema, NamingConvention convention, out string? projection)
    {
        projection = null;

        // With an explicit `returning`, the UPDATE RETURNs rows shaped like a select (003 FR-017); otherwise
        // it returns the affected-row count (the default + the optimistic-concurrency conflict signal).
        if (command.Returning is { } shape)
        {
            var statementR = BuildStatement(command, entity, schema, convention, shape, out var bindsR);
            return EmitShapedMethod(command, entity, shape, statementR, bindsR, out projection);
        }

        var statement = BuildStatement(command, entity, schema, convention, null, out var binds);
        return EmitWriteMethod(command, statement, binds);
    }

    private static string EmitDelete(CommandModel command, EntityModel entity, string schema, NamingConvention convention, out string? projection)
    {
        projection = null;

        if (command.Returning is { } shape)
        {
            var statementR = BuildStatement(command, entity, schema, convention, shape, out var bindsR);
            return EmitShapedMethod(command, entity, shape, statementR, bindsR, out projection);
        }

        var statement = BuildStatement(command, entity, schema, convention, null, out var binds);
        return EmitWriteMethod(command, statement, binds);
    }

    // The RETURNING column list (database names) for a result shape: Entity → all columns; Projection → the
    // projected members; Scalar → the single member.
    private static List<string> ReturningColumns(ReturningShape shape, EntityModel entity, NamingConvention convention) =>
        shape.Kind == ReturningKind.Entity
            ? entity.Properties.Select(x => Col(x.Name, x.NameOverride, convention)).ToList()
            : shape.Members.Select(m =>
            {
                var prop = entity.Properties.First(x => x.Name == m);
                return Col(prop.Name, prop.NameOverride, convention);
            }).ToList();

    // Emits a method whose statement RETURNs rows, materialized per the result shape (entity / projection /
    // scalar) — shared by insert and by update/delete with an explicit `returning` (003 FR-017).
    private static string EmitShapedMethod(CommandModel command, EntityModel entity, ReturningShape shape, SqlStatement statement, List<string> binds, out string? projection)
    {
        projection = null;
        if (shape.Kind == ReturningKind.Scalar)
        {
            var property = entity.Properties.First(x => x.Name == shape.Members[0]);
            var clr = property.IsNullable ? property.ClrType + "?" : property.ClrType;
            var read = property.IsNullable
                ? $"reader.IsNull(0) ? null : reader.GetValue<{property.ClrType}>(0)"
                : $"reader.GetValue<{property.ClrType}>(0)";
            var ws = OpenMethod(command, $"global::System.Threading.Tasks.ValueTask<{clr}>");
            EmitStatement(ws, statement, binds);
            ws
                .Line($"var command = new {Abs}.Querying.CompiledCommand<{clr}>(statement, static reader => {read});")
                .Line("return await session.ExecuteCommandAsync(command, cancellationToken).ConfigureAwait(false);")
                .Close();
            return ws.ToString().TrimEnd('\n');
        }

        if (shape.Kind == ReturningKind.Projection)
        {
            var resultType = Naming.ToPascalCase(command.Name) + "Result";
            var members = shape.Members.ToArray();
            var recordFields = members.Select(m =>
            {
                var prop = entity.Properties.First(x => x.Name == m);
                var clr = prop.IsNullable ? prop.ClrType + "?" : prop.ClrType;
                return $"{clr} {Naming.ToPascalCase(m)}";
            });
            projection = $"public sealed record {resultType}({string.Join(", ", recordFields)});";

            var args = members.Select((m, i) =>
            {
                var prop = entity.Properties.First(x => x.Name == m);
                var read = $"reader.GetValue<{prop.ClrType}>({i})";
                return prop.IsNullable ? $"reader.IsNull({i}) ? null : {read}" : read;
            });

            var wp = OpenMethod(command, $"global::System.Threading.Tasks.ValueTask<{resultType}>");
            EmitStatement(wp, statement, binds);
            wp
                .Line($"var command = new {Abs}.Querying.CompiledCommand<{resultType}>(statement, static reader => new {resultType}({string.Join(", ", args)}));")
                .Line("return await session.ExecuteCommandAsync(command, cancellationToken).ConfigureAwait(false);")
                .Close();
            return wp.ToString().TrimEnd('\n');
        }

        // Entity (default) → the full immutable entity via its generated ctor.
        var w = OpenMethod(command, $"global::System.Threading.Tasks.ValueTask<{entity.Name}>");
        EmitStatement(w, statement, binds);
        w
            .Line($"var command = new {Abs}.Querying.CompiledCommand<{entity.Name}>(statement, static reader => new {entity.Name}(reader));")
            .Line("return await session.ExecuteCommandAsync(command, cancellationToken).ConfigureAwait(false);")
            .Close();
        return w.ToString().TrimEnd('\n');
    }

    // Resolves an assignment's target database column + its value. The target is either a value property or a
    // single reference (FR-020/021): `alias.author = expr` writes the `author_id` FK column (no json cast;
    // the value is the target's primary key).
    private static (string Column, SqlValue Value) ResolveAssignment(
        Assignment assignment, EntityModel entity, NamingConvention convention, ref int p, List<string> binds)
    {
        var property = entity.Properties.FirstOrDefault(x => x.Name == assignment.Column);
        if (property is not null)
        {
            return (
                Col(property.Name, property.NameOverride, convention),
                BuildValue(assignment.Value, property.DslType == "json", ref p, binds));
        }

        var reference = entity.References.First(r => r.Kind == ReferenceKind.Ref && r.Name == assignment.Column);
        return (
            NamingConventions.Resolve(reference.Name, null, convention) + "_id",
            BuildValue(assignment.Value, json: false, ref p, binds));
    }

    // The neutral value for an assignment: param/literal → a bound positional parameter (the dialect renders
    // its placeholder + any json cast); native → an inline native call (the dialect spells it out).
    private static SqlValue BuildValue(CommandValue value, bool json, ref int p, List<string> binds)
    {
        switch (value.Kind)
        {
            // A `with`-bound name (WithRef) is a method-level C# local with exactly that name, so it binds
            // just like a parameter (FR-021).
            case CommandValueKind.Parameter:
            case CommandValueKind.WithRef:
                p++;
                binds.Add($"writer.Write({p}, {value.Text});");
                return new ParamValue(p, json);
            case CommandValueKind.StringLiteral:
                p++;
                binds.Add($"writer.Write({p}, {Quote(value.Text)});");
                return new ParamValue(p, json);
            case CommandValueKind.NumberLiteral:
                p++;
                binds.Add($"writer.Write({p}, {value.Text});");
                return new ParamValue(p, json);
            default: // NativeCall
                return new NativeValue(value.Text);
        }
    }

    private static List<SqlCondition> BuildWhere(CommandModel command, EntityModel entity, NamingConvention convention, ref int p, List<string> binds)
    {
        var where = new List<SqlCondition>(command.Filters.Count);
        foreach (var filter in command.Filters)
        {
            var property = entity.Properties.First(x => x.Name == filter.Column);
            p++;
            where.Add(new SqlCondition(Col(property.Name, property.NameOverride, convention), OperatorSql(filter.Op), p));
            binds.Add($"writer.Write({p}, {filter.ParameterName});");
        }

        return where;
    }

    private static SourceWriter OpenMethod(CommandModel command, string returnType)
    {
        // 003: the authored snake_case unit name becomes a PascalCase C# method.
        var methodName = Naming.ToPascalCase(command.Name);
        var declared = string.Join(", ", command.Parameters.Select(x => $"{x.ClrType} {x.Name}"));
        var parameterList = declared.Length > 0 ? declared + ", " : string.Empty;
        return new SourceWriter()
            .Open($"public async {returnType} {methodName}({parameterList}global::System.Threading.CancellationToken cancellationToken = default)");
    }

    private static void EmitStatement(SourceWriter w, SqlStatement statement, List<string> binds) =>
        WriteStatement(w, "statement", statement, binds);

    // Emits `var {stmtVar} = new PreparedStatement(<dialect switch>, writer => { binds });`.
    private static void WriteStatement(SourceWriter w, string stmtVar, SqlStatement statement, List<string> binds)
    {
        w.Line($"var {stmtVar} = new {Abs}.Querying.PreparedStatement(");
        DialectSwitch.WriteStatementArg(w, "    ", "session.Dialect", statement, ",");
        w
            .Line("    writer =>")
            .Line("    {");
        foreach (var bind in binds)
        {
            w.Line("        " + bind);
        }

        w.Line("    });");
    }

    // update/delete return the affected-row count (0 on a stale concurrency token → caller's conflict).
    private static string EmitWriteMethod(CommandModel command, SqlStatement statement, List<string> binds)
    {
        var w = OpenMethod(command, "global::System.Threading.Tasks.ValueTask<int>");
        EmitStatement(w, statement, binds);
        w.Line("return await session.ExecuteWriteAsync(statement, cancellationToken).ConfigureAwait(false);").Close();
        return w.ToString().TrimEnd('\n');
    }

    private static string Col(string name, string? nameOverride, NamingConvention convention) =>
        NamingConventions.Resolve(name, nameOverride, convention);

    private static string OperatorSql(CompareOp op) => op switch
    {
        CompareOp.Eq => "=",
        CompareOp.Neq => "<>",
        CompareOp.Lt => "<",
        CompareOp.Gt => ">",
        CompareOp.Le => "<=",
        CompareOp.Ge => ">=",
        CompareOp.Like => "LIKE",
        CompareOp.ILike => "ILIKE",
        _ => "=",
    };

    private static string Quote(string text) =>
        "\"" + text.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    private static DiagnosticInfo Diag(
        Microsoft.CodeAnalysis.DiagnosticDescriptor descriptor,
        string filePath,
        params string[] args) =>
        new(descriptor, new LocationInfo(filePath, default, default), new EquatableArray<string>(args));
}
