using System.Collections.Generic;
using System.Linq;
using Dormant.SourceGeneration.Diagnostics;
using Dormant.SourceGeneration.Emit;
using Dormant.SourceGeneration.Ir;
using Dormant.SourceGeneration.Parsing;

namespace Dormant.SourceGeneration.Query;

/// <summary>
/// Emits, per DormantQL query file, a <c>partial static</c> <c>{Module}Queries</c> class of extension
/// methods on <c>ISession</c> (one per query), each carrying build-time SQL on a <c>CompiledQuery&lt;T&gt;</c>
/// plus a no-boxing materializer (FR-006/FR-007/FR-013). Full-entity queries materialize via the entity's
/// generated ctor; flat projections emit a distinct <c>record</c> with exactly the requested members
/// (FR-008). Folds tasks T053 (projection type), T054 (SELECT SQL), T055 (query method). Semantic errors
/// (unknown entity/column/parameter) are reported as ORM010/ORM011/ORM012 and the offending query is
/// skipped while valid siblings still emit.
/// </summary>
internal static class QueryEmitter
{
    private const string Abs = "global::Dormant.Abstractions";

    /// <summary>Emits the query class source and collects any semantic diagnostics.</summary>
    public static (string? Source, IReadOnlyList<DiagnosticInfo> Diagnostics) Emit(
        string @namespace,
        QueryFile file,
        IReadOnlyDictionary<string, EntityModel> entities,
        NamingConvention convention)
    {
        var diagnostics = new List<DiagnosticInfo>();
        var bodies = new List<string>();
        var projections = new List<string>();

        foreach (var query in file.Queries)
        {
            if (!entities.TryGetValue(query.RootEntity, out var entity))
            {
                diagnostics.Add(Diag(
                    DiagnosticDescriptors.UnknownQueryEntity, file.FilePath, query.Name, query.RootEntity));
                continue;
            }

            if (!Validate(query, entity, file.FilePath, diagnostics))
            {
                continue;
            }

            bodies.Add(EmitMethod(query, entity, convention, out var projection));
            if (projection is not null)
            {
                projections.Add(projection);
            }
        }

        if (bodies.Count == 0)
        {
            return (null, diagnostics);
        }

        var className = Naming.ToPascalCase(file.ModuleName) + "Queries";
        var writer = new SourceWriter()
            .Line("// <auto-generated/>")
            .Line("#nullable enable")
            .Line()
            .Line($"namespace {@namespace};")
            .Line()
            .Open($"public static partial class {className}")
            // C# 14 extension block (FR-058): lets the generated surface grow to extension
            // properties/static members without a breaking shape change. The receiver `session` is in
            // scope for every member, so the method bodies reference it directly.
            .Open($"extension({Abs}.Sessions.ISession session)");

        foreach (var body in bodies)
        {
            foreach (var line in body.Split('\n'))
            {
                writer.Line(line);
            }
        }

        writer.Close().Close().Line();

        foreach (var projection in projections)
        {
            writer.Line(projection);
        }

        return (writer.ToString(), diagnostics);
    }

    private static bool Validate(
        QueryModel query,
        EntityModel entity,
        string filePath,
        List<DiagnosticInfo> diagnostics)
    {
        var ok = true;
        var columns = new HashSet<string>(entity.Properties.Select(p => p.Name), System.StringComparer.Ordinal);
        var parameters = new HashSet<string>(query.Parameters.Select(p => p.Name), System.StringComparer.Ordinal);

        void Column(string column)
        {
            if (!columns.Contains(column))
            {
                diagnostics.Add(Diag(
                    DiagnosticDescriptors.UnknownQueryColumn, filePath, query.Name, column, entity.Name));
                ok = false;
            }
        }

        void Parameter(string parameter)
        {
            if (!parameters.Contains(parameter))
            {
                diagnostics.Add(Diag(
                    DiagnosticDescriptors.UnknownQueryParameter, filePath, query.Name, parameter));
                ok = false;
            }
        }

        foreach (var field in query.ProjectionFields)
        {
            Column(field);
        }

        foreach (var filter in query.Filters)
        {
            Column(filter.Column);
            Parameter(filter.ParameterName);
        }

        foreach (var term in query.OrderBy)
        {
            Column(term.Column);
        }

        if (query.Limit is { IsParameter: true } limit)
        {
            Parameter(limit.ParameterName);
        }

        if (query.Offset is { IsParameter: true } offset)
        {
            Parameter(offset.ParameterName);
        }

        return ok;
    }

    private static string EmitMethod(QueryModel query, EntityModel entity, NamingConvention convention, out string? projection)
    {
        var parameterOrder = new List<string>();
        var sql = BuildSql(query, entity, convention, parameterOrder);

        string resultType;
        string materializer;
        if (query.IsProjection)
        {
            resultType = query.Name + "Result";
            projection = BuildProjectionRecord(resultType, query, entity);
            materializer = BuildProjectionMaterializer(resultType, query, entity);
        }
        else
        {
            resultType = entity.Name;
            projection = null;
            materializer = $"static reader => new {entity.Name}(reader)";
        }

        var declared = string.Join(
            ", ",
            query.Parameters.Select(p => $"{p.ClrType} {p.Name}"));
        var parameterList = declared.Length > 0 ? declared + ", " : string.Empty;

        // Inside the extension block the receiver `session` is implicit — no `this` parameter, and the
        // member is an instance-style extension method (public, non-static).
        var writer = new SourceWriter()
            .Open($"public global::System.Collections.Generic.IAsyncEnumerable<{resultType}> {query.Name}({parameterList}global::System.Threading.CancellationToken cancellationToken = default)")
            .Line($"var statement = new {Abs}.Querying.PreparedStatement(")
            .Line($"    {Quote(sql)},")
            .Line("    writer =>")
            .Line("    {");

        for (var i = 0; i < parameterOrder.Count; i++)
        {
            writer.Line($"        writer.Write({i + 1}, {parameterOrder[i]});");
        }

        writer
            .Line("    });")
            .Line($"var query = new {Abs}.Querying.CompiledQuery<{resultType}>(statement, {materializer});")
            .Line("return session.QueryAsync(query, cancellationToken);")
            .Close();

        return writer.ToString().TrimEnd('\n');
    }

    // Builds the SELECT as a structured IR node (FR-059) and renders it; populates parameterOrder (the
    // bind-callback order) as positional parameters are assigned. Database names resolved via the active
    // convention / per-unit overrides (FR-052/FR-054/FR-055).
    private static string BuildSql(QueryModel query, EntityModel entity, NamingConvention convention, List<string> parameterOrder)
    {
        var columns = query.IsProjection
            ? query.ProjectionFields.Select(f => ColByName(entity, f, convention)).ToList()
            : entity.Properties.Select(p => NamingConventions.Resolve(p.Name, p.NameOverride, convention)).ToList();

        var where = new List<SqlCondition>(query.Filters.Count);
        foreach (var filter in query.Filters)
        {
            parameterOrder.Add(filter.ParameterName);
            where.Add(new SqlCondition(
                ColByName(entity, filter.Column, convention), OperatorSql(filter.Op), parameterOrder.Count));
        }

        var orderBy = query.OrderBy
            .Select(t => new SqlOrder(ColByName(entity, t.Column, convention), t.Descending))
            .ToList();

        var statement = new SelectStatement(
            NamingConventions.Resolve(entity.Name, entity.NameOverride, convention),
            columns,
            where,
            orderBy,
            ToLimit(query.Limit, parameterOrder),
            ToLimit(query.Offset, parameterOrder));

        return SqlRenderer.Render(statement);
    }

    private static SqlLimit? ToLimit(LimitValue? value, List<string> parameterOrder)
    {
        if (value is null)
        {
            return null;
        }

        if (!value.IsParameter)
        {
            return new SqlLimit(IsParameter: false, ParameterIndex: 0, value.Literal);
        }

        parameterOrder.Add(value.ParameterName);
        return new SqlLimit(IsParameter: true, parameterOrder.Count, Literal: 0);
    }

    private static string BuildProjectionRecord(string resultType, QueryModel query, EntityModel entity)
    {
        var fields = query.ProjectionFields.Select(field =>
        {
            var property = entity.Properties.First(p => p.Name == field);
            var clr = property.IsNullable ? property.ClrType + "?" : property.ClrType;
            return $"{clr} {Naming.ToPascalCase(field)}";
        });
        return $"public sealed record {resultType}({string.Join(", ", fields)});";
    }

    private static string BuildProjectionMaterializer(string resultType, QueryModel query, EntityModel entity)
    {
        var args = query.ProjectionFields.Select((field, i) =>
        {
            var property = entity.Properties.First(p => p.Name == field);
            var read = $"reader.GetValue<{property.ClrType}>({i})";
            return property.IsNullable
                ? $"reader.IsNull({i}) ? null : {read}"
                : read;
        });
        return $"static reader => new {resultType}({string.Join(", ", args)})";
    }

    private static string OperatorSql(CompareOp op) => op switch
    {
        CompareOp.Eq => "=",
        CompareOp.Lt => "<",
        CompareOp.Gt => ">",
        CompareOp.Le => "<=",
        CompareOp.Ge => ">=",
        CompareOp.Like => "LIKE",
        CompareOp.ILike => "ILIKE",
        _ => "=",
    };

    // Resolves a column's database name from its DSL name, honoring the property's explicit override.
    private static string ColByName(EntityModel entity, string dslName, NamingConvention convention)
    {
        var property = entity.Properties.FirstOrDefault(p => p.Name == dslName);
        return property is null
            ? NamingConventions.Resolve(dslName, null, convention)
            : NamingConventions.Resolve(property.Name, property.NameOverride, convention);
    }

    private static string Quote(string text) =>
        "\"" + text.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    private static DiagnosticInfo Diag(
        Microsoft.CodeAnalysis.DiagnosticDescriptor descriptor,
        string filePath,
        params string[] args) =>
        new(descriptor, new LocationInfo(filePath, default, default), new EquatableArray<string>(args));
}
