using System.Collections.Generic;
using System.Linq;
using Dormant.SourceGeneration.Diagnostics;
using Dormant.SourceGeneration.Emit;
using Dormant.SourceGeneration.Ir;
using Dormant.SourceGeneration.Parsing;

namespace Dormant.SourceGeneration.Query;

/// <summary>
/// Emits, per DormantQL query file, a <c>partial static</c> <c>{Module}Queries</c> class of extension
/// methods on <c>ISession</c> (one per query), each carrying build-time SQL on a <c>CompiledQuery&lt;T&gt;</c>
/// plus a no-boxing materializer (FR-006/FR-007/FR-013). Full-entity queries materialize via the entity's
/// generated ctor; flat projections emit a distinct <c>record</c> with exactly the requested members
/// (FR-008). Folds tasks T053 (projection type), T054 (SELECT SQL), T055 (query method). Semantic errors
/// (unknown entity/column/parameter) are reported as ORM010/ORM011/ORM012 and the offending query is
/// skipped while valid siblings still emit.
/// </summary>
internal static class QueryEmitter
{
    private const string Abs = "global::Dormant.Abstractions";

    /// <summary>Emits the query class source and collects any semantic diagnostics.</summary>
    public static (string? Source, IReadOnlyList<DiagnosticInfo> Diagnostics) Emit(
        string @namespace,
        QueryFile file,
        IReadOnlyDictionary<string, (EntityModel Entity, string Schema)> entities,
        NamingConvention convention
    )
    {
        var diagnostics = new List<DiagnosticInfo>();
        var bodies = new List<string>();
        var projections = new List<string>();

        foreach (var query in file.Queries)
        {
            if (!entities.TryGetValue(query.RootEntity, out var entry))
            {
                diagnostics.Add(
                    Diag(
                        DiagnosticDescriptors.UnknownQueryEntity,
                        file.FilePath,
                        query.Name,
                        query.RootEntity
                    )
                );
                continue;
            }

            if (!Validate(query, entry.Entity, file.FilePath, diagnostics))
            {
                continue;
            }

            bodies.Add(
                EmitMethod(query, entry.Entity, entry.Schema, convention, out var projection)
            );
            if (projection is not null)
            {
                projections.Add(projection);
            }
        }

        if (bodies.Count == 0)
        {
            return (null, diagnostics);
        }

        var className = Naming.ToPascalCase(file.ModuleName) + "Queries";
        var writer = new SourceWriter()
            .Line("// <auto-generated/>")
            .Line("#nullable enable")
            .Line()
            .Line($"namespace {@namespace};")
            .Line()
            .Open($"public static partial class {className}")
            // C# 14 extension block (FR-058): lets the generated surface grow to extension
            // properties/static members without a breaking shape change. The receiver `session` is in
            // scope for every member, so the method bodies reference it directly.
            .Open($"extension({Abs}.Sessions.ISession session)");

        foreach (var body in bodies)
        {
            foreach (var line in body.Split('\n'))
            {
                writer.Line(line);
            }
        }

        writer.Close().Close().Line();

        foreach (var projection in projections)
        {
            writer.Line(projection);
        }

        return (writer.ToString(), diagnostics);
    }

    private static bool Validate(
        QueryModel query,
        EntityModel entity,
        string filePath,
        List<DiagnosticInfo> diagnostics
    )
    {
        var ok = true;
        var columns = new HashSet<string>(
            entity.Properties.Select(p => p.Name),
            System.StringComparer.Ordinal
        );
        var parameters = new HashSet<string>(
            query.Parameters.Select(p => p.Name),
            System.StringComparer.Ordinal
        );

        void Column(string column)
        {
            if (!columns.Contains(column))
            {
                diagnostics.Add(
                    Diag(
                        DiagnosticDescriptors.UnknownQueryColumn,
                        filePath,
                        query.Name,
                        column,
                        entity.Name
                    )
                );
                ok = false;
            }
        }

        void Parameter(string parameter)
        {
            if (!parameters.Contains(parameter))
            {
                diagnostics.Add(
                    Diag(
                        DiagnosticDescriptors.UnknownQueryParameter,
                        filePath,
                        query.Name,
                        parameter
                    )
                );
                ok = false;
            }
        }

        foreach (var field in query.ProjectionFields)
        {
            Column(field);
        }

        foreach (var filter in query.Filters)
        {
            Column(filter.Column);
            Parameter(filter.ParameterName);
        }

        foreach (var term in query.OrderBy)
        {
            Column(term.Column);
        }

        if (query.Limit is { IsParameter: true } limit)
        {
            Parameter(limit.ParameterName);
        }

        if (query.Offset is { IsParameter: true } offset)
        {
            Parameter(offset.ParameterName);
        }

        return ok;
    }

    private static string EmitMethod(
        QueryModel query,
        EntityModel entity,
        string schema,
        NamingConvention convention,
        out string? projection
    )
    {
        // 003: the authored snake_case unit name becomes a PascalCase C# method; the projection record
        // mirrors it ({Method}Result).
        var methodName = Naming.ToPascalCase(query.Name);
        string resultType;
        string materializer;
        if (query.IsProjection)
        {
            resultType = methodName + "Result";
            projection = BuildProjectionRecord(resultType, query, entity);
            materializer = BuildProjectionMaterializer(resultType, query, entity);
        }
        else
        {
            resultType = entity.Name;
            projection = null;
            materializer = $"static reader => new {entity.Name}(reader)";
        }

        // Required parameters first, optional last (C# default-value ordering); optional value types
        // become nullable and default to null (FR-012/FR-031).
        var declared = string.Join(
            ", ",
            query
                .Parameters.OrderBy(p => p.IsOptional)
                .Select(p =>
                    p.IsOptional ? $"{p.ClrType}? {p.Name} = default" : $"{p.ClrType} {p.Name}"
                )
        );
        var parameterList = declared.Length > 0 ? declared + ", " : string.Empty;

        var optionalNames = new HashSet<string>(
            query.Parameters.Where(p => p.IsOptional).Select(p => p.Name),
            System.StringComparer.Ordinal
        );
        var dynamic = query.Filters.Any(f => optionalNames.Contains(f.ParameterName));

        // Inside the extension block the receiver `session` is implicit — no `this` parameter.
        var writer = new SourceWriter().Open(
            $"public global::System.Collections.Generic.IAsyncEnumerable<{resultType}> {methodName}({parameterList}global::System.Threading.CancellationToken cancellationToken = default)"
        );

        if (dynamic)
        {
            EmitDynamicStatement(writer, query, entity, schema, convention, optionalNames);
        }
        else
        {
            EmitStaticStatement(writer, query, entity, schema, convention);
        }

        writer
            .Line(
                $"var query = new {Abs}.Querying.CompiledQuery<{resultType}>(statement, {materializer});"
            )
            .Line("return session.QueryAsync(query, cancellationToken);")
            .Close();

        return writer.ToString().TrimEnd('\n');
    }

    // No optional filters: the SQL is fully known at build time (IR-rendered) with a fixed bind order.
    private static void EmitStaticStatement(
        SourceWriter writer,
        QueryModel query,
        EntityModel entity,
        string schema,
        NamingConvention convention
    )
    {
        var parameterOrder = new List<string>();
        var sql = BuildSql(query, entity, schema, convention, parameterOrder);

        writer.Line($"var statement = new {Abs}.Querying.PreparedStatement(");
        writer.RawArg("    ", sql, ",");
        writer.Line("    writer =>").Line("    {");

        for (var i = 0; i < parameterOrder.Count; i++)
        {
            writer.Line($"        writer.Write({i + 1}, {parameterOrder[i]});");
        }

        writer.Line("    });");
    }

    // Optional filters present: SQL is assembled at runtime by including a filter's fragment only when
    // its parameter is supplied (FR-031 fragment selection — NOT query compilation, FR-013). The result
    // type is fixed regardless of which fragments are chosen (FR-005). Mirrors the change-tracking UPDATE.
    private static void EmitDynamicStatement(
        SourceWriter writer,
        QueryModel query,
        EntityModel entity,
        string schema,
        NamingConvention convention,
        HashSet<string> optionalNames
    )
    {
        var cols = (
            query.IsProjection
                ? query.ProjectionFields.Select(f => ColByName(entity, f, convention))
                : entity.Properties.Select(p =>
                    NamingConventions.Resolve(p.Name, p.NameOverride, convention)
                )
        ).Select(Lit);
        var tableLit =
            Lit(schema)
            + "."
            + Lit(NamingConventions.Resolve(entity.Name, entity.NameOverride, convention));

        writer
            .Line(
                $"var sql = new global::System.Text.StringBuilder(\"SELECT {string.Join(", ", cols)} FROM {tableLit}\");"
            )
            .Line("int p = 0;")
            .Line("var conds = new global::System.Collections.Generic.List<string>();");

        // Required filters always contribute; optional filters only when their parameter is non-null.
        foreach (var filter in query.Filters)
        {
            var fragment =
                $"\"{Lit(ColByName(entity, filter.Column, convention))} {OperatorSql(filter.Op)} $\" + (++p)";
            if (optionalNames.Contains(filter.ParameterName))
            {
                writer.Line($"if ({filter.ParameterName} != null) {{ conds.Add({fragment}); }}");
            }
            else
            {
                writer.Line($"conds.Add({fragment});");
            }
        }

        writer.Line(
            "if (conds.Count > 0) { sql.Append(\" WHERE \").Append(string.Join(\" AND \", conds)); }"
        );

        if (query.OrderBy.Count > 0)
        {
            var orderLit = string.Join(
                ", ",
                query.OrderBy.Select(t =>
                    Lit(ColByName(entity, t.Column, convention)) + (t.Descending ? " DESC" : " ASC")
                )
            );
            writer.Line($"sql.Append(\" ORDER BY {orderLit}\");");
        }

        EmitDynamicLimit(writer, "LIMIT", query.Limit, optionalNames);
        EmitDynamicLimit(writer, "OFFSET", query.Offset, optionalNames);

        writer
            .Line($"var statement = new {Abs}.Querying.PreparedStatement(sql.ToString(), writer =>")
            .Line("{")
            .Line("    int i = 0;");

        foreach (var filter in query.Filters)
        {
            var value = BindExpression(filter.ParameterName, query);
            if (optionalNames.Contains(filter.ParameterName))
            {
                writer.Line(
                    $"    if ({filter.ParameterName} != null) {{ writer.Write(++i, {value}); }}"
                );
            }
            else
            {
                writer.Line($"    writer.Write(++i, {value});");
            }
        }

        EmitDynamicLimitBind(writer, query.Limit, query);
        EmitDynamicLimitBind(writer, query.Offset, query);
        writer.Line("});");
    }

    private static void EmitDynamicLimit(
        SourceWriter writer,
        string keyword,
        LimitValue? limit,
        HashSet<string> optionalNames
    )
    {
        if (limit is null)
        {
            return;
        }

        // Optional LIMIT/OFFSET parameters are a later slice; here they are literals or required params.
        if (limit.IsParameter)
        {
            writer.Line($"sql.Append(\" {keyword} $\").Append(++p);");
        }
        else
        {
            writer.Line(
                $"sql.Append(\" {keyword} {limit.Literal.ToString(System.Globalization.CultureInfo.InvariantCulture)}\");"
            );
        }
    }

    private static void EmitDynamicLimitBind(
        SourceWriter writer,
        LimitValue? limit,
        QueryModel query
    )
    {
        if (limit is { IsParameter: true })
        {
            writer.Line($"    writer.Write(++i, {BindExpression(limit.ParameterName, query)});");
        }
    }

    // The bind expression for a parameter: value-type optionals are unwrapped via `.Value` (the guard
    // guarantees non-null); reference types pass through.
    private static string BindExpression(string parameterName, QueryModel query)
    {
        var parameter = query.Parameters.FirstOrDefault(p => p.Name == parameterName);
        if (parameter is { IsOptional: true } && IsValueType(parameter.ClrType))
        {
            return parameterName + ".Value";
        }

        return parameterName;
    }

    private static bool IsValueType(string clrType) => clrType is not ("string" or "byte[]");

    // C#-source representation of a quoted SQL identifier (the chars \"name\") for runtime StringBuilder seeds.
    private static string Lit(string identifier) => "\\\"" + identifier + "\\\"";

    // Builds the SELECT as a structured IR node (FR-059) and renders it; populates parameterOrder (the
    // bind-callback order) as positional parameters are assigned. Database names resolved via the active
    // convention / per-unit overrides (FR-052/FR-054/FR-055).
    private static string BuildSql(
        QueryModel query,
        EntityModel entity,
        string schema,
        NamingConvention convention,
        List<string> parameterOrder
    )
    {
        var columns = query.IsProjection
            ? query.ProjectionFields.Select(f => ColByName(entity, f, convention)).ToList()
            : entity
                .Properties.Select(p =>
                    NamingConventions.Resolve(p.Name, p.NameOverride, convention)
                )
                .ToList();

        var where = new List<SqlCondition>(query.Filters.Count);
        foreach (var filter in query.Filters)
        {
            parameterOrder.Add(filter.ParameterName);
            where.Add(
                new SqlCondition(
                    ColByName(entity, filter.Column, convention),
                    OperatorSql(filter.Op),
                    parameterOrder.Count
                )
            );
        }

        var orderBy = query
            .OrderBy.Select(t => new SqlOrder(
                ColByName(entity, t.Column, convention),
                t.Descending
            ))
            .ToList();

        var statement = new SelectStatement(
            new TableRef(
                schema,
                NamingConventions.Resolve(entity.Name, entity.NameOverride, convention)
            ),
            columns,
            where,
            orderBy,
            ToLimit(query.Limit, parameterOrder),
            ToLimit(query.Offset, parameterOrder)
        );

        return SqlRenderer.Render(statement);
    }

    private static SqlLimit? ToLimit(LimitValue? value, List<string> parameterOrder)
    {
        if (value is null)
        {
            return null;
        }

        if (!value.IsParameter)
        {
            return new SqlLimit(IsParameter: false, ParameterIndex: 0, value.Literal);
        }

        parameterOrder.Add(value.ParameterName);
        return new SqlLimit(IsParameter: true, parameterOrder.Count, Literal: 0);
    }

    private static string BuildProjectionRecord(
        string resultType,
        QueryModel query,
        EntityModel entity
    )
    {
        var fields = query.ProjectionFields.Select(field =>
        {
            var property = entity.Properties.First(p => p.Name == field);
            var clr = property.IsNullable ? property.ClrType + "?" : property.ClrType;
            return $"{clr} {Naming.ToPascalCase(field)}";
        });
        return $"public sealed record {resultType}({string.Join(", ", fields)});";
    }

    private static string BuildProjectionMaterializer(
        string resultType,
        QueryModel query,
        EntityModel entity
    )
    {
        var args = query.ProjectionFields.Select(
            (field, i) =>
            {
                var property = entity.Properties.First(p => p.Name == field);
                var read = $"reader.GetValue<{property.ClrType}>({i})";
                return property.IsNullable ? $"reader.IsNull({i}) ? null : {read}" : read;
            }
        );
        return $"static reader => new {resultType}({string.Join(", ", args)})";
    }

    private static string OperatorSql(CompareOp op) =>
        op switch
        {
            CompareOp.Eq => "=",
            CompareOp.Neq => "<>",
            CompareOp.Lt => "<",
            CompareOp.Gt => ">",
            CompareOp.Le => "<=",
            CompareOp.Ge => ">=",
            CompareOp.Like => "LIKE",
            CompareOp.ILike => "ILIKE",
            _ => "=",
        };

    // Resolves a column's database name from its DSL name, honoring the property's explicit override.
    private static string ColByName(EntityModel entity, string dslName, NamingConvention convention)
    {
        var property = entity.Properties.FirstOrDefault(p => p.Name == dslName);
        return property is null
            ? NamingConventions.Resolve(dslName, null, convention)
            : NamingConventions.Resolve(property.Name, property.NameOverride, convention);
    }

    private static DiagnosticInfo Diag(
        Microsoft.CodeAnalysis.DiagnosticDescriptor descriptor,
        string filePath,
        params string[] args
    ) =>
        new(
            descriptor,
            new LocationInfo(filePath, default, default),
            new EquatableArray<string>(args)
        );
}
