using System.Collections.Generic;
using System.Linq;
using Dormant.SourceGeneration.Diagnostics;
using Dormant.SourceGeneration.Emit;
using Dormant.SourceGeneration.Ir;
using Dormant.SourceGeneration.Ir.Dialects;
using Dormant.SourceGeneration.Parsing;
using Dormant.SourceGeneration.Schema;

namespace Dormant.SourceGeneration.Query;

/// <summary>
/// Emits, per DormantQL query file, a <c>partial static</c> <c>{Module}Queries</c> class of extension
/// methods on <c>ISession</c> (one per query), each carrying build-time SQL on a <c>CompiledQuery&lt;T&gt;</c>
/// plus a no-boxing materializer (FR-006/FR-007/FR-013). Full-entity queries materialize via the entity's
/// generated ctor; flat projections emit a distinct <c>record</c> with exactly the requested members
/// (FR-008). Folds tasks T053 (projection type), T054 (SELECT SQL), T055 (query method). Semantic errors
/// (unknown entity/column/parameter) are reported as ORM010/ORM011/ORM012 and the offending query is
/// skipped while valid siblings still emit.
/// </summary>
internal static class QueryEmitter
{
    private const string Abs = "global::Dormant.Abstractions";

    /// <summary>Emits the query class source and collects any semantic diagnostics.</summary>
    public static (string? Source, IReadOnlyList<DiagnosticInfo> Diagnostics) Emit(
        string @namespace,
        QueryFile file,
        IReadOnlyDictionary<string, (EntityModel Entity, string Schema)> entities,
        NamingConvention convention
    )
    {
        var diagnostics = new List<DiagnosticInfo>();
        var bodies = new List<string>();
        var projections = new List<string>();
        var helpers = new List<string>();

        foreach (var query in file.Queries)
        {
            if (!entities.TryGetValue(query.RootEntity, out var entry))
            {
                diagnostics.Add(
                    Diag(
                        DiagnosticDescriptors.UnknownQueryEntity,
                        file.FilePath,
                        query.Name,
                        query.RootEntity
                    )
                );
                continue;
            }

            if (!Validate(query, entry.Entity, file.FilePath, diagnostics, entities))
            {
                continue;
            }

            bodies.Add(
                EmitMethod(
                    query,
                    entry.Entity,
                    entry.Schema,
                    convention,
                    entities,
                    out var projection,
                    out var queryHelpers
                )
            );
            if (projection is not null)
            {
                projections.Add(projection);
            }

            if (queryHelpers is not null)
            {
                helpers.Add(queryHelpers);
            }
        }

        if (bodies.Count == 0)
        {
            return (null, diagnostics);
        }

        var className = Naming.ToPascalCase(file.ModuleName) + "Queries";
        var writer = new SourceWriter()
            .Line("// <auto-generated/>")
            .Line("#nullable enable")
            .Line()
            .Line($"namespace {@namespace};")
            .Line()
            .Open($"public static partial class {className}")
            // C# 14 extension block (FR-058): lets the generated surface grow to extension
            // properties/static members without a breaking shape change. The receiver `session` is in
            // scope for every member, so the method bodies reference it directly.
            .Open($"extension({Abs}.Sessions.ISession session)");

        foreach (var body in bodies)
        {
            foreach (var line in body.Split('\n'))
            {
                writer.Line(line);
            }
        }

        writer.Close(); // close the extension block

        // JSON-parse helpers (to-many materialization) are plain static methods on the query class — in
        // scope for the materializer lambdas, but outside the extension block.
        foreach (var helper in helpers)
        {
            foreach (var line in helper.Split('\n'))
            {
                writer.Line(line);
            }
        }

        writer.Close().Line(); // close the class

        foreach (var projection in projections)
        {
            writer.Line(projection);
        }

        return (writer.ToString(), diagnostics);
    }

    private static bool Validate(
        QueryModel query,
        EntityModel entity,
        string filePath,
        List<DiagnosticInfo> diagnostics,
        IReadOnlyDictionary<string, (EntityModel Entity, string Schema)> entities
    )
    {
        var ok = true;
        var columns = new HashSet<string>(
            entity.Properties.Select(p => p.Name),
            System.StringComparer.Ordinal
        );
        var parameters = new HashSet<string>(
            query.Parameters.Select(p => p.Name),
            System.StringComparer.Ordinal
        );

        void Column(string column)
        {
            if (!columns.Contains(column))
            {
                diagnostics.Add(
                    Diag(
                        DiagnosticDescriptors.UnknownQueryColumn,
                        filePath,
                        query.Name,
                        column,
                        entity.Name
                    )
                );
                ok = false;
            }
        }

        void Parameter(string parameter)
        {
            if (!parameters.Contains(parameter))
            {
                diagnostics.Add(
                    Diag(
                        DiagnosticDescriptors.UnknownQueryParameter,
                        filePath,
                        query.Name,
                        parameter
                    )
                );
                ok = false;
            }
        }

        foreach (var field in query.ProjectionFields)
        {
            Column(field);
        }

        foreach (var filter in query.Filters)
        {
            if (filter.NavRefs.Count == 0)
            {
                Column(filter.Column);
            }
            else
            {
                // 009 P-B: navigate the to-one reference chain, then check the terminal column on the target.
                var cur = entity;
                var navOk = true;
                foreach (var refName in filter.NavRefs)
                {
                    var reference = cur.References.FirstOrDefault(r =>
                        r.Kind == ReferenceKind.Ref && r.Name == refName
                    );
                    if (
                        reference is null
                        || !entities.TryGetValue(reference.TargetEntity, out var target)
                    )
                    {
                        diagnostics.Add(
                            Diag(
                                DiagnosticDescriptors.UnknownQueryColumn,
                                filePath,
                                query.Name,
                                refName,
                                cur.Name
                            )
                        );
                        navOk = false;
                        ok = false;
                        break;
                    }

                    cur = target.Entity;
                }

                if (navOk && !cur.Properties.Any(p => p.Name == filter.Column))
                {
                    diagnostics.Add(
                        Diag(
                            DiagnosticDescriptors.UnknownQueryColumn,
                            filePath,
                            query.Name,
                            filter.Column,
                            cur.Name
                        )
                    );
                    ok = false;
                }
            }

            Parameter(filter.ParameterName);
        }

        foreach (var term in query.OrderBy)
        {
            Column(term.Column);
        }

        if (query.Limit is { IsParameter: true } limit)
        {
            Parameter(limit.ParameterName);
        }

        if (query.Offset is { IsParameter: true } offset)
        {
            Parameter(offset.ParameterName);
        }

        if (query.IsShaped)
        {
            ok &= ValidateShape(
                query.Name,
                query.Shape!.Nodes,
                entity,
                filePath,
                diagnostics,
                entities
            );
        }

        return ok;
    }

    private static string EmitMethod(
        QueryModel query,
        EntityModel entity,
        string schema,
        NamingConvention convention,
        IReadOnlyDictionary<string, (EntityModel Entity, string Schema)> entities,
        out string? projection,
        out string? helpers
    )
    {
        helpers = null;
        // 003: the authored snake_case unit name becomes a PascalCase C# method; the projection record
        // mirrors it ({Method}Result).
        var methodName = Naming.ToPascalCase(query.Name);
        string resultType;
        string materializer;
        if (query.IsShaped)
        {
            // 009 US1: an EdgeQL-style root-object shape → a nested immutable record tree. To-one nests via
            // a JOIN + positional read; to-many nests via a JSON-array correlated subquery parsed into a list.
            resultType = methodName + "Result";
            var records = new List<string>();
            BuildShapeRecords(
                resultType,
                query.Shape!.Nodes,
                entity,
                entities,
                convention,
                records
            );
            projection = string.Join("\n", records);
            var helperMethods = new List<string>();
            materializer = BuildShapeMaterializer(
                resultType,
                query,
                entity,
                convention,
                entities,
                helperMethods
            );
            helpers = helperMethods.Count > 0 ? string.Join("\n", helperMethods) : null;
        }
        else if (query.IsProjection)
        {
            resultType = methodName + "Result";
            projection = BuildProjectionRecord(resultType, query, entity);
            materializer = BuildProjectionMaterializer(resultType, query, entity);
        }
        else
        {
            resultType = entity.Name;
            projection = null;
            materializer = $"static reader => new {entity.Name}(reader)";
        }

        // Required parameters first, optional last (C# default-value ordering); optional value types
        // become nullable and default to null (FR-012/FR-031).
        var declared = string.Join(
            ", ",
            query
                .Parameters.OrderBy(p => p.IsOptional)
                .Select(p =>
                    p.IsOptional ? $"{p.ClrType}? {p.Name} = default" : $"{p.ClrType} {p.Name}"
                )
        );
        var parameterList = declared.Length > 0 ? declared + ", " : string.Empty;

        var optionalNames = new HashSet<string>(
            query.Parameters.Where(p => p.IsOptional).Select(p => p.Name),
            System.StringComparer.Ordinal
        );
        // 009 P-B: a query that navigates a relationship uses the relational (joined) SQL path. Navigation
        // combined with optional-parameter fragment selection is not supported yet; nav forces the static path.
        var hasNav = query.Filters.Any(f => f.NavRefs.Count > 0);
        var dynamic = !hasNav && query.Filters.Any(f => optionalNames.Contains(f.ParameterName));

        // Inside the extension block the receiver `session` is implicit — no `this` parameter.
        var writer = new SourceWriter().Open(
            $"public global::System.Collections.Generic.IAsyncEnumerable<{resultType}> {methodName}({parameterList}global::System.Threading.CancellationToken cancellationToken = default)"
        );

        if (dynamic)
        {
            EmitDynamicStatement(writer, query, entity, schema, convention, optionalNames);
        }
        else
        {
            EmitStaticStatement(writer, query, entity, schema, convention, entities);
        }

        writer
            .Line(
                $"var query = new {Abs}.Querying.CompiledQuery<{resultType}>(statement, {materializer});"
            )
            .Line("return session.QueryAsync(query, cancellationToken);")
            .Close();

        return writer.ToString().TrimEnd('\n');
    }

    // No optional filters: the SQL is fully known at build time (one IR-rendered variant per dialect,
    // selected by session.Dialect) with a fixed bind order.
    private static void EmitStaticStatement(
        SourceWriter writer,
        QueryModel query,
        EntityModel entity,
        string schema,
        NamingConvention convention,
        IReadOnlyDictionary<string, (EntityModel Entity, string Schema)> entities
    )
    {
        var parameterOrder = new List<string>();
        SqlStatement select;
        if (query.IsShaped)
        {
            select = BuildShapeSelect(query, entity, schema, convention, entities, parameterOrder);
        }
        else if (query.Filters.Any(f => f.NavRefs.Count > 0))
        {
            select = BuildJoinedSelect(query, entity, schema, convention, entities, parameterOrder);
        }
        else
        {
            select = BuildSelect(query, entity, schema, convention, parameterOrder);
        }

        writer.Line($"var statement = new {Abs}.Querying.PreparedStatement(");
        DialectSwitch.WriteStatementArg(writer, "    ", "session.Dialect", select, ",");
        writer.Line("    writer =>").Line("    {");

        for (var i = 0; i < parameterOrder.Count; i++)
        {
            writer.Line($"        writer.Write({i + 1}, {parameterOrder[i]});");
        }

        writer.Line("    });");
    }

    // Optional filters present: SQL is assembled at runtime by including a filter's fragment only when
    // its parameter is supplied (FR-031 fragment selection — NOT query compilation, FR-013). The result
    // type is fixed regardless of which fragments are chosen (FR-005). Mirrors the change-tracking UPDATE.
    private static void EmitDynamicStatement(
        SourceWriter writer,
        QueryModel query,
        EntityModel entity,
        string schema,
        NamingConvention convention,
        HashSet<string> optionalNames
    )
    {
        var colNames = query.IsProjection
            ? query.ProjectionFields.Select(f => ColByName(entity, f, convention)).ToList()
            : EntityColumns.SelectColumnNames(entity, convention);
        var tableName = NamingConventions.Resolve(entity.Name, entity.NameOverride, convention);

        // The static seed (SELECT cols FROM table) varies by dialect (table qualification); the dynamic WHERE
        // fragments below append per-dialect placeholders via the Ph local (fragment selection, FR-031 — NOT
        // SQL compilation). Column quoting is identical across v1 dialects, so fragments use build-time literals.
        writer.Line("var sql = new global::System.Text.StringBuilder(");
        DialectSwitch.WriteSwitchArg(
            writer,
            "    ",
            "session.Dialect",
            r =>
                "SELECT "
                + string.Join(", ", colNames.Select(r.Quote))
                + " FROM "
                + r.QualifyTable(schema, tableName),
            ");"
        );
        writer
            .Line("int p = 0;")
            .Line("var conds = new global::System.Collections.Generic.List<string>();");
        EmitPlaceholderLocal(writer);

        // Required filters always contribute; optional filters only when their parameter is non-null.
        foreach (var filter in query.Filters)
        {
            var fragment =
                $"\"{Lit(ColByName(entity, filter.Column, convention))} {OperatorSql(filter.Op)} \" + Ph(++p)";
            if (optionalNames.Contains(filter.ParameterName))
            {
                writer.Line($"if ({filter.ParameterName} != null) {{ conds.Add({fragment}); }}");
            }
            else
            {
                writer.Line($"conds.Add({fragment});");
            }
        }

        writer.Line(
            "if (conds.Count > 0) { sql.Append(\" WHERE \").Append(string.Join(\" AND \", conds)); }"
        );

        if (query.OrderBy.Count > 0)
        {
            var orderLit = string.Join(
                ", ",
                query.OrderBy.Select(t =>
                    Lit(ColByName(entity, t.Column, convention)) + (t.Descending ? " DESC" : " ASC")
                )
            );
            writer.Line($"sql.Append(\" ORDER BY {orderLit}\");");
        }

        EmitDynamicLimit(writer, "LIMIT", query.Limit);
        EmitDynamicLimit(writer, "OFFSET", query.Offset);

        writer
            .Line($"var statement = new {Abs}.Querying.PreparedStatement(sql.ToString(), writer =>")
            .Line("{")
            .Line("    int i = 0;");

        foreach (var filter in query.Filters)
        {
            var value = BindExpression(filter.ParameterName, query);
            if (optionalNames.Contains(filter.ParameterName))
            {
                writer.Line(
                    $"    if ({filter.ParameterName} != null) {{ writer.Write(++i, {value}); }}"
                );
            }
            else
            {
                writer.Line($"    writer.Write(++i, {value});");
            }
        }

        EmitDynamicLimitBind(writer, query.Limit, query);
        EmitDynamicLimitBind(writer, query.Offset, query);
        writer.Line("});");
    }

    // The runtime positional-placeholder builder for the dynamic path: one arm per registered dialect
    // (PostgreSQL ⇒ "$" + n, SQLite ⇒ "?"). A local function so each fragment reads naturally as `Ph(++p)`.
    private static void EmitPlaceholderLocal(SourceWriter writer)
    {
        writer.Line("string Ph(int n) => session.Dialect switch");
        writer.Line("{");
        foreach (var renderer in Ir.Dialects.DialectRenderers.All)
        {
            writer.Line(
                $"    global::Dormant.Abstractions.Providers.DialectId.{renderer.EnumMember} => {renderer.DynamicPlaceholderExpr("n")},"
            );
        }

        writer.Line(
            "    _ => throw new global::System.NotSupportedException(\"Dormant: no SQL variant for dialect \" + session.Dialect + \".\"),"
        );
        writer.Line("};");
    }

    private static void EmitDynamicLimit(SourceWriter writer, string keyword, LimitValue? limit)
    {
        if (limit is null)
        {
            return;
        }

        // Optional LIMIT/OFFSET parameters are a later slice; here they are literals or required params.
        if (limit.IsParameter)
        {
            writer.Line($"sql.Append(\" {keyword} \").Append(Ph(++p));");
        }
        else
        {
            writer.Line(
                $"sql.Append(\" {keyword} {limit.Literal.ToString(System.Globalization.CultureInfo.InvariantCulture)}\");"
            );
        }
    }

    private static void EmitDynamicLimitBind(
        SourceWriter writer,
        LimitValue? limit,
        QueryModel query
    )
    {
        if (limit is { IsParameter: true })
        {
            writer.Line($"    writer.Write(++i, {BindExpression(limit.ParameterName, query)});");
        }
    }

    // The bind expression for a parameter: value-type optionals are unwrapped via `.Value` (the guard
    // guarantees non-null); reference types pass through.
    private static string BindExpression(string parameterName, QueryModel query)
    {
        var parameter = query.Parameters.FirstOrDefault(p => p.Name == parameterName);
        if (parameter is { IsOptional: true } && IsValueType(parameter.ClrType))
        {
            return parameterName + ".Value";
        }

        return parameterName;
    }

    private static bool IsValueType(string clrType) => clrType is not ("string" or "byte[]");

    // C#-source representation of a quoted SQL identifier (the chars \"name\") for runtime StringBuilder seeds.
    private static string Lit(string identifier) => "\\\"" + identifier + "\\\"";

    // Builds the SELECT as a structured IR node (FR-059) and renders it; populates parameterOrder (the
    // bind-callback order) as positional parameters are assigned. Database names resolved via the active
    // convention / per-unit overrides (FR-052/FR-054/FR-055).
    private static SelectStatement BuildSelect(
        QueryModel query,
        EntityModel entity,
        string schema,
        NamingConvention convention,
        List<string> parameterOrder
    )
    {
        var columns = query.IsProjection
            ? query.ProjectionFields.Select(f => ColByName(entity, f, convention)).ToList()
            : EntityColumns.SelectColumnNames(entity, convention);

        var where = new List<SqlCondition>(query.Filters.Count);
        foreach (var filter in query.Filters)
        {
            parameterOrder.Add(filter.ParameterName);
            where.Add(
                new SqlCondition(
                    ColByName(entity, filter.Column, convention),
                    OperatorSql(filter.Op),
                    parameterOrder.Count
                )
            );
        }

        var orderBy = query
            .OrderBy.Select(t => new SqlOrder(
                ColByName(entity, t.Column, convention),
                t.Descending
            ))
            .ToList();

        return new SelectStatement(
            new TableRef(
                schema,
                NamingConventions.Resolve(entity.Name, entity.NameOverride, convention)
            ),
            columns,
            where,
            orderBy,
            ToLimit(query.Limit, parameterOrder),
            ToLimit(query.Offset, parameterOrder)
        );
    }

    // 009 P-B: builds the relational (joined) SELECT for a query that navigates to-one references in its
    // WHERE. Root columns are selected (qualified by the root alias, same order as the flat path so the
    // materializer is unchanged); each distinct navigated reference becomes a LEFT JOIN on its `<ref>_id`
    // FK to the target's primary key; filters render over the owning alias's column.
    private static JoinedSelectStatement BuildJoinedSelect(
        QueryModel query,
        EntityModel entity,
        string schema,
        NamingConvention convention,
        IReadOnlyDictionary<string, (EntityModel Entity, string Schema)> entities,
        List<string> parameterOrder
    )
    {
        var rootAlias = query.Alias;
        var rootFrom = new FromItem(
            new TableRef(
                schema,
                NamingConventions.Resolve(entity.Name, entity.NameOverride, convention)
            ),
            rootAlias
        );

        var joins = new List<SqlJoin>();
        var aliasEntities = new Dictionary<string, EntityModel>(System.StringComparer.Ordinal)
        {
            [rootAlias] = entity,
        };
        var joined = new HashSet<string>(System.StringComparer.Ordinal);

        foreach (var filter in query.Filters.Where(f => f.NavRefs.Count > 0))
        {
            var prevAlias = rootAlias;
            var cur = entity;
            foreach (var refName in filter.NavRefs)
            {
                var reference = cur.References.First(r =>
                    r.Kind == ReferenceKind.Ref && r.Name == refName
                );
                var target = entities[reference.TargetEntity];
                if (joined.Add(refName))
                {
                    var targetTable = NamingConventions.Resolve(
                        target.Entity.Name,
                        target.Entity.NameOverride,
                        convention
                    );
                    var targetPk = target.Entity.Properties.First(p => p.IsPrimary);
                    var targetPkCol = NamingConventions.Resolve(
                        targetPk.Name,
                        targetPk.NameOverride,
                        convention
                    );
                    joins.Add(
                        new SqlJoin(
                            new FromItem(new TableRef(target.Schema, targetTable), refName),
                            JoinKind.Left,
                            new BinaryExpr(
                                new ColumnExpr(
                                    prevAlias,
                                    EntityColumns.ForeignKeyColumn(reference, convention)
                                ),
                                "=",
                                new ColumnExpr(refName, targetPkCol)
                            )
                        )
                    );
                    aliasEntities[refName] = target.Entity;
                }

                prevAlias = refName;
                cur = target.Entity;
            }
        }

        var itemCols = query.IsProjection
            ? query.ProjectionFields.Select(f => ColByName(entity, f, convention)).ToList()
            : EntityColumns.SelectColumnNames(entity, convention);
        var items = itemCols.Select(c => new SqlSelectItem(new ColumnExpr(rootAlias, c))).ToList();

        var where = new List<SqlExpr>(query.Filters.Count);
        foreach (var filter in query.Filters)
        {
            var ownerAlias =
                filter.NavRefs.Count == 0 ? rootAlias : filter.NavRefs[filter.NavRefs.Count - 1];
            var ownerEntity = aliasEntities[ownerAlias];
            parameterOrder.Add(filter.ParameterName);
            where.Add(
                new BinaryExpr(
                    new ColumnExpr(ownerAlias, ColByName(ownerEntity, filter.Column, convention)),
                    OperatorSql(filter.Op),
                    new ParamExpr(parameterOrder.Count)
                )
            );
        }

        var orderBy = query
            .OrderBy.Select(t => new SqlOrderExpr(
                new ColumnExpr(rootAlias, ColByName(entity, t.Column, convention)),
                t.Descending
            ))
            .ToList();

        return new JoinedSelectStatement(
            rootFrom,
            joins,
            items,
            where,
            orderBy,
            ToLimit(query.Limit, parameterOrder),
            ToLimit(query.Offset, parameterOrder)
        );
    }

    // 009 US1: build the JOIN-flattened relational SELECT for a root-object shape — root + a JOIN per
    // to-one reference node, columns in depth-first shape order (matching the materializer). Where/order
    // are own-column on the root for this slice (navigation-in-shape-where is a later slice).
    private static JoinedSelectStatement BuildShapeSelect(
        QueryModel query,
        EntityModel entity,
        string schema,
        NamingConvention convention,
        IReadOnlyDictionary<string, (EntityModel Entity, string Schema)> entities,
        List<string> parameterOrder
    )
    {
        var rootAlias = query.Alias;
        var rootFrom = new FromItem(
            new TableRef(
                schema,
                NamingConventions.Resolve(entity.Name, entity.NameOverride, convention)
            ),
            rootAlias
        );

        var items = new List<SqlSelectItem>();
        var joins = new List<SqlJoin>();
        var ord = new int[1];
        _ = BuildShapeLevel(
            string.Empty,
            query.Shape!.Nodes,
            rootAlias,
            entity,
            rootAlias,
            convention,
            entities,
            items,
            joins,
            ord,
            new List<string>()
        );

        var where = new List<SqlExpr>(query.Filters.Count);
        foreach (var filter in query.Filters)
        {
            parameterOrder.Add(filter.ParameterName);
            where.Add(
                new BinaryExpr(
                    new ColumnExpr(rootAlias, ColByName(entity, filter.Column, convention)),
                    OperatorSql(filter.Op),
                    new ParamExpr(parameterOrder.Count)
                )
            );
        }

        var orderBy = query
            .OrderBy.Select(t => new SqlOrderExpr(
                new ColumnExpr(rootAlias, ColByName(entity, t.Column, convention)),
                t.Descending
            ))
            .ToList();

        return new JoinedSelectStatement(
            rootFrom,
            joins,
            items,
            where,
            orderBy,
            ToLimit(query.Limit, parameterOrder),
            ToLimit(query.Offset, parameterOrder)
        );
    }

    private static string BuildShapeMaterializer(
        string resultType,
        QueryModel query,
        EntityModel entity,
        NamingConvention convention,
        IReadOnlyDictionary<string, (EntityModel Entity, string Schema)> entities,
        List<string> helpers
    )
    {
        var items = new List<SqlSelectItem>();
        var joins = new List<SqlJoin>();
        var ord = new int[1];
        var rootArgs = BuildShapeLevel(
            resultType,
            query.Shape!.Nodes,
            query.Alias,
            entity,
            query.Alias,
            convention,
            entities,
            items,
            joins,
            ord,
            helpers
        );
        return $"static reader => new {resultType}({rootArgs})";
    }

    // The single shared traversal: appends SELECT items + JOINs and returns this record level's
    // constructor arguments. Column order is depth-first (scalar ⇒ one column; to-one ⇒ a target-PK probe
    // column then the nested columns), so the materializer ordinals always match the SELECT.
    private static string BuildShapeLevel(
        string recordType,
        EquatableArray<ShapeNode> nodes,
        string ownerAlias,
        EntityModel ownerEntity,
        string rootAlias,
        NamingConvention convention,
        IReadOnlyDictionary<string, (EntityModel Entity, string Schema)> entities,
        List<SqlSelectItem> items,
        List<SqlJoin> joins,
        int[] ord,
        List<string> helpers
    )
    {
        var args = new List<string>();
        foreach (var node in nodes)
        {
            if (!node.IsRef)
            {
                var prop = ownerEntity.Properties.First(p => p.Name == node.Name);
                items.Add(
                    new SqlSelectItem(
                        new ColumnExpr(
                            ownerAlias,
                            NamingConventions.Resolve(prop.Name, prop.NameOverride, convention)
                        )
                    )
                );
                var read = $"reader.GetValue<{prop.ClrType}>({ord[0]})";
                args.Add(prop.IsNullable ? $"reader.IsNull({ord[0]}) ? null : {read}" : read);
                ord[0]++;
                continue;
            }

            var reference = ownerEntity.References.First(r => r.Name == node.Name);
            var target = entities[reference.TargetEntity];
            var childRecordType = recordType + Naming.ToPascalCase(node.Name);

            if (reference.Kind != ReferenceKind.Ref)
            {
                // to-many (009 US1): a correlated JSON-array subquery over the child relation, parsed into
                // an IReadOnlyList at materialize. Backlink = the child's to-one ref pointing back here.
                var collectionAlias = node.Name;
                var inverse = target.Entity.References.First(r =>
                    r.Kind == ReferenceKind.Ref && r.TargetEntity == ownerEntity.Name
                );
                var ownerPk = ownerEntity.Properties.First(p => p.IsPrimary);
                var elementMembers = node
                    .Children.Select(c =>
                    {
                        var cp = target.Entity.Properties.First(p => p.Name == c.Name);
                        return new JsonMember(
                            c.Name,
                            new ColumnExpr(
                                collectionAlias,
                                NamingConventions.Resolve(cp.Name, cp.NameOverride, convention)
                            )
                        );
                    })
                    .ToList();
                items.Add(
                    new SqlSelectItem(
                        new JsonArrayAggSubquery(
                            new FromItem(
                                new TableRef(
                                    target.Schema,
                                    NamingConventions.Resolve(
                                        target.Entity.Name,
                                        target.Entity.NameOverride,
                                        convention
                                    )
                                ),
                                collectionAlias
                            ),
                            new JsonObjectExpr(elementMembers),
                            [
                                new BinaryExpr(
                                    new ColumnExpr(
                                        collectionAlias,
                                        EntityColumns.ForeignKeyColumn(inverse, convention)
                                    ),
                                    "=",
                                    new ColumnExpr(
                                        ownerAlias,
                                        NamingConventions.Resolve(
                                            ownerPk.Name,
                                            ownerPk.NameOverride,
                                            convention
                                        )
                                    )
                                ),
                            ]
                        )
                    )
                );
                args.Add($"Parse{childRecordType}(reader.GetValue<string>({ord[0]}))");
                ord[0]++;
                EmitJsonListParser(childRecordType, node.Children, target.Entity, helpers);
                continue;
            }

            // to-one: JOIN + target-PK probe column + recurse.
            var childAlias = ownerAlias == rootAlias ? node.Name : ownerAlias + "_" + node.Name;
            var targetPk = target.Entity.Properties.First(p => p.IsPrimary);
            var targetPkCol = NamingConventions.Resolve(
                targetPk.Name,
                targetPk.NameOverride,
                convention
            );
            joins.Add(
                new SqlJoin(
                    new FromItem(
                        new TableRef(
                            target.Schema,
                            NamingConventions.Resolve(
                                target.Entity.Name,
                                target.Entity.NameOverride,
                                convention
                            )
                        ),
                        childAlias
                    ),
                    reference.IsRequired ? JoinKind.Inner : JoinKind.Left,
                    new BinaryExpr(
                        new ColumnExpr(
                            ownerAlias,
                            EntityColumns.ForeignKeyColumn(reference, convention)
                        ),
                        "=",
                        new ColumnExpr(childAlias, targetPkCol)
                    )
                )
            );

            // Probe column (target PK) precedes the nested fields: an absent optional ref reads null here.
            items.Add(new SqlSelectItem(new ColumnExpr(childAlias, targetPkCol)));
            var probeOrd = ord[0];
            ord[0]++;

            var childArgs = BuildShapeLevel(
                childRecordType,
                node.Children,
                childAlias,
                target.Entity,
                rootAlias,
                convention,
                entities,
                items,
                joins,
                ord,
                helpers
            );
            var construct = $"new {childRecordType}({childArgs})";
            args.Add(
                reference.IsRequired ? construct : $"reader.IsNull({probeOrd}) ? null : {construct}"
            );
        }

        return string.Join(", ", args);
    }

    // Emits the JSON-array parser for a to-many element record: JsonDocument-based (reflection-free,
    // AOT-safe). A Utf8JsonReader optimization is a later perf task.
    private static void EmitJsonListParser(
        string elementType,
        EquatableArray<ShapeNode> children,
        EntityModel elementEntity,
        List<string> helpers
    )
    {
        var args = children.Select(c =>
        {
            var prop = elementEntity.Properties.First(p => p.Name == c.Name);
            return JsonElementGet(prop.ClrType, prop.IsNullable, c.Name);
        });

        var writer = new SourceWriter()
            .Open(
                $"private static global::System.Collections.Generic.IReadOnlyList<{elementType}> Parse{elementType}(string json)"
            )
            .Line("using var doc = global::System.Text.Json.JsonDocument.Parse(json);")
            .Line(
                $"var list = new global::System.Collections.Generic.List<{elementType}>(doc.RootElement.GetArrayLength());"
            )
            .Open("foreach (var e in doc.RootElement.EnumerateArray())")
            .Line($"list.Add(new {elementType}({string.Join(", ", args)}));")
            .Close()
            .Line("return list;")
            .Close();
        helpers.Add(writer.ToString().TrimEnd('\n'));
    }

    // The JsonElement accessor for a scalar CLR type (used by the to-many element parser).
    private static string JsonElementGet(string clrType, bool nullable, string key)
    {
        var access = $"e.GetProperty(\"{key}\")";
        var getter = clrType switch
        {
            "string" => $"{access}.GetString()!",
            "int" => $"{access}.GetInt32()",
            "long" => $"{access}.GetInt64()",
            "short" => $"{access}.GetInt16()",
            "bool" => $"{access}.GetBoolean()",
            "double" => $"{access}.GetDouble()",
            "float" => $"{access}.GetSingle()",
            "decimal" => $"{access}.GetDecimal()",
            "global::System.Guid" => $"global::System.Guid.Parse({access}.GetString()!)",
            "global::System.DateTime" =>
                $"global::System.DateTime.Parse({access}.GetString()!, global::System.Globalization.CultureInfo.InvariantCulture)",
            _ => $"{access}.GetString()!",
        };

        return nullable
            ? $"{access}.ValueKind == global::System.Text.Json.JsonValueKind.Null ? ({clrType}?)null : {getter}"
            : getter;
    }

    // Emits the nested immutable record(s) matching the shape (recursive: a record per to-one node).
    private static void BuildShapeRecords(
        string recordType,
        EquatableArray<ShapeNode> nodes,
        EntityModel entity,
        IReadOnlyDictionary<string, (EntityModel Entity, string Schema)> entities,
        NamingConvention convention,
        List<string> output
    )
    {
        var members = new List<string>();
        var children =
            new List<(string Type, EquatableArray<ShapeNode> Nodes, EntityModel Entity)>();

        foreach (var node in nodes)
        {
            if (!node.IsRef)
            {
                var prop = entity.Properties.First(p => p.Name == node.Name);
                var clr = prop.IsNullable ? prop.ClrType + "?" : prop.ClrType;
                members.Add($"{clr} {Naming.ToPascalCase(node.Name)}");
                continue;
            }

            var reference = entity.References.First(r => r.Name == node.Name);
            var target = entities[reference.TargetEntity];
            var childType = recordType + Naming.ToPascalCase(node.Name);
            var memberType =
                reference.Kind != ReferenceKind.Ref
                    ? $"global::System.Collections.Generic.IReadOnlyList<{childType}>"
                : reference.IsRequired ? childType
                : childType + "?";
            members.Add($"{memberType} {Naming.ToPascalCase(node.Name)}");
            children.Add((childType, node.Children, target.Entity));
        }

        output.Add($"public sealed record {recordType}({string.Join(", ", members)});");

        foreach (var child in children)
        {
            BuildShapeRecords(child.Type, child.Nodes, child.Entity, entities, convention, output);
        }
    }

    // Validates a shape: scalar nodes must be properties; reference nodes must be declared to-one refs
    // whose target resolves; recurse into the target. Reuses the column diagnostic for unknown members.
    private static bool ValidateShape(
        string queryName,
        EquatableArray<ShapeNode> nodes,
        EntityModel entity,
        string filePath,
        List<DiagnosticInfo> diagnostics,
        IReadOnlyDictionary<string, (EntityModel Entity, string Schema)> entities
    )
    {
        var ok = true;
        foreach (var node in nodes)
        {
            if (!node.IsRef)
            {
                if (!entity.Properties.Any(p => p.Name == node.Name))
                {
                    diagnostics.Add(
                        Diag(
                            DiagnosticDescriptors.UnknownQueryColumn,
                            filePath,
                            queryName,
                            node.Name,
                            entity.Name
                        )
                    );
                    ok = false;
                }

                continue;
            }

            var reference = entity.References.FirstOrDefault(r => r.Name == node.Name);
            if (reference is null || !entities.TryGetValue(reference.TargetEntity, out var target))
            {
                diagnostics.Add(
                    Diag(
                        DiagnosticDescriptors.UnknownQueryColumn,
                        filePath,
                        queryName,
                        node.Name,
                        entity.Name
                    )
                );
                ok = false;
                continue;
            }

            ok &= ValidateShape(
                queryName,
                node.Children,
                target.Entity,
                filePath,
                diagnostics,
                entities
            );
        }

        return ok;
    }

    private static SqlLimit? ToLimit(LimitValue? value, List<string> parameterOrder)
    {
        if (value is null)
        {
            return null;
        }

        if (!value.IsParameter)
        {
            return new SqlLimit(IsParameter: false, ParameterIndex: 0, value.Literal);
        }

        parameterOrder.Add(value.ParameterName);
        return new SqlLimit(IsParameter: true, parameterOrder.Count, Literal: 0);
    }

    private static string BuildProjectionRecord(
        string resultType,
        QueryModel query,
        EntityModel entity
    )
    {
        var fields = query.ProjectionFields.Select(field =>
        {
            var property = entity.Properties.First(p => p.Name == field);
            var clr = property.IsNullable ? property.ClrType + "?" : property.ClrType;
            return $"{clr} {Naming.ToPascalCase(field)}";
        });
        return $"public sealed record {resultType}({string.Join(", ", fields)});";
    }

    private static string BuildProjectionMaterializer(
        string resultType,
        QueryModel query,
        EntityModel entity
    )
    {
        var args = query.ProjectionFields.Select(
            (field, i) =>
            {
                var property = entity.Properties.First(p => p.Name == field);
                var read = $"reader.GetValue<{property.ClrType}>({i})";
                return property.IsNullable ? $"reader.IsNull({i}) ? null : {read}" : read;
            }
        );
        return $"static reader => new {resultType}({string.Join(", ", args)})";
    }

    private static string OperatorSql(CompareOp op) =>
        op switch
        {
            CompareOp.Eq => "=",
            CompareOp.Neq => "<>",
            CompareOp.Lt => "<",
            CompareOp.Gt => ">",
            CompareOp.Le => "<=",
            CompareOp.Ge => ">=",
            CompareOp.Like => "LIKE",
            CompareOp.ILike => "ILIKE",
            _ => "=",
        };

    // Resolves a column's database name from its DSL name, honoring the property's explicit override.
    private static string ColByName(EntityModel entity, string dslName, NamingConvention convention)
    {
        var property = entity.Properties.FirstOrDefault(p => p.Name == dslName);
        return property is null
            ? NamingConventions.Resolve(dslName, null, convention)
            : NamingConventions.Resolve(property.Name, property.NameOverride, convention);
    }

    private static DiagnosticInfo Diag(
        Microsoft.CodeAnalysis.DiagnosticDescriptor descriptor,
        string filePath,
        params string[] args
    ) =>
        new(
            descriptor,
            new LocationInfo(filePath, default, default),
            new EquatableArray<string>(args)
        );
}
